### ISSUE TITLE
org.apache.velocity.exception.ParseErrorException occurs when i use Hyperlink in the xdoc report template

### ISSUE THREAD

**Issue by premmasarani** [opensagres/xdocreport#112]
hi,
I'm using xdocreport in my web application facing following issue.
When i use any Hyperlink in the xdoc report template It gives following exception

org.apache.velocity.exception.ParseErrorException: Lexical error,   Encountered: "a" (97), after : "&" at fr.opensagres.xdocreport.document.docx.DocxReport@3f52c19d!word/document.xml[line 1, column 3287]
	at org.apache.velocity.Template.process(Template.java:151)
	at org.apache.velocity.runtime.resource.ResourceManagerImpl.loadResource(ResourceManagerImpl.java:437)
	at org.apache.velocity.runtime.resource.ResourceManagerImpl.getResource(ResourceManagerImpl.java:352)
	at org.apache.velocity.runtime.RuntimeInstance.getTemplate(RuntimeInstance.java:1533)
	at org.apache.velocity.app.VelocityEngine.getTemplate(VelocityEngine.java:392)
	at fr.opensagres.xdocreport.template.velocity.internal.VelocityTemplateEngine.processWithCache(VelocityTemplateEngine.java:97)
	at fr.opensagres.xdocreport.template.AbstractTemplateEngine.process(AbstractTemplateEngine.java:111)
	at fr.opensagres.xdocreport.template.AbstractTemplateEngine.process(AbstractTemplateEngine.java:83)
	at fr.opensagres.xdocreport.document.AbstractXDocReport.processTemplateEngine(AbstractXDocReport.java:775)
	at fr.opensagres.xdocreport.document.AbstractXDocReport.process(AbstractXDocReport.java:521)
	at fr.opensagres.xdocreport.document.AbstractXDocReport.process(AbstractXDocReport.java:487)

========================
It works fine when i don't use any hyperlinks
I'm attaching both templates(with hyperlink and without hyperlink) . Both are identical just one contains one hyperlink.
Can u please guide, why its giving this error and any way to overcome this?

[Simple_Test_Case's.docx](https://github.com/opensagres/xdocreport/files/113871/Simple_Test_Case.s.docx)
[Simple_Test_Case's -with_link.docx](https://github.com/opensagres/xdocreport/files/113872/Simple_Test_Case.s.-with_link.docx)

**Comment by angelozerr** [comment]
I think your problem is not because of hyperlink but because you are not using mergefields to set Velocity directive.

Please takes time to read https://github.com/opensagres/xdocreport/wiki/DocxReportingQuickStart

**Comment by premmasarani** [comment]
hi @angelozerr , thaks for your quick respond.
It worked for me when i used mergefields. but i would like to know Is this the only possible way to add static mergefields in docx ?
I'm also using some static texts with formatting(see attached docx). It didn't required to use mergefields. so why static hyperlinks creating problems?

[Simple_Test_Case's.docx](https://github.com/opensagres/xdocreport/files/114063/Simple_Test_Case.s.docx)

**Comment by angelozerr** [comment]
If you update your Simple_Test_Case's -with_link.docx with mergefield by keeping your link, it should work, no?

**Comment by premmasarani** [comment]
Yes It worked.

**Comment by premmasarani** [comment]
So is it a limitation or standard that we must have to use mergefield for hyperlink.

**Comment by angelozerr** [comment]
> So is it a limitation or standard that we must have to use mergefield for hyperlink.

No, why do you say that? The rule is :

 * use hyperlink (without mergefield)
 * use mergefield for set any Velocity directive and don't set it directly inside ms word

*  "Simple_Test_Case's.docx" uses mergefield. If you add an hyperlink it should work again.
* "Simple_Test_Case's -with_link.docx" doesn't use mergefield. I don't speak about your hyperlink, I speak about for instance «#set($sheetTitle='First Isheet')» which doesn't use mergefield. So teh problem is not about the hyperlink but about not the use of mergefield for «#set($sheetTitle='First Isheet')»

**Comment by premmasarani** [comment]
Thanks angelozerr. Got your point.
Still have some queries. Here I have attached two documents. Both are identical except one contains Hyperlink.
Nd here Have used mergefield for set any Velocity directive. still having problems
[TemplateWithLink.docx](https://github.com/opensagres/xdocreport/files/117008/TemplateWithLink.docx)
[TemplateWithoutLink.docx](https://github.com/opensagres/xdocreport/files/117009/TemplateWithoutLink.docx)

**Comment by premmasarani** [comment]
Nd here is another Problem.
I have attached my demo app's java classes and Docx template.
I Have used mergefield for set any Velocity directives .When I use any hyperlink in Docx file The document with the link generated, but the dynamic values remained inside the << >> brackets.
see the attached generated report.
On removing Hyperlinks it works perfectly.
Please suggest if u can.
[XDocReport.java.txt](https://github.com/opensagres/xdocreport/files/117096/XDocReport.java.txt)
[XDocReportHelper.java.txt](https://github.com/opensagres/xdocreport/files/117097/XDocReportHelper.java.txt)
[xDocTemplate.docx](https://github.com/opensagres/xdocreport/files/117098/xDocTemplate.docx)
[GeneratedResult.docx](https://github.com/opensagres/xdocreport/files/117099/GeneratedResult.docx)

**Comment by angelozerr** [comment]
At first please attach sampel which works. You don't put in the context some context with the key "" although your docx xDocTemplate.docx defines "XDocReportHelper.name". 

I have modify your Java code to put the well context and when I generate report it works well with 1.0.5 and 1.0.6-SNAPSHOT. Which version of XDocReport do you use?

**Comment by premmasarani** [comment]
Hi @angelozerr ,Thanks for your help. It solved my issue on upgrading XDocReport to 1.0.4.
Is it the final stable branch?
That is what i got from here https://code.google.com/archive/p/xdocreport/downloads.
if 1.0.5 or 1.0.6 stable release is available then can u please give link for these jars?

**Comment by angelozerr** [comment]
> Thanks for your help. It solved my issue on upgrading XDocReport to 1.0.4.

That's cool. Next time please tell us which version of XDocReport you are using. It will avoid loosing our time to test something which is working. Thanks!

> That is what i got from here https://code.google.com/archive/p/xdocreport/downloads.

This google project was given up/ Now we are using github. It exists https://github.com/opensagres/xdocreport/releases but if I remember it doesn't contains compiled JARs of XDocReport (just the sources).

So the last stable version of XDocReport is 1.0.5 You can see this info at https://github.com/opensagres/xdocreport/ and you must use maven to download JARs (we have no time to create zip/jar to download like we have done with google project.

I think we will release soon 1.0.6
