### ISSUE TITLE
Different header on second page.

### ISSUE THREAD

**Issue by luisalves00** [opensagres/xdocreport#135]
I need a different header on the second page. It's like a summary of info that is on the main page, that should appear on every following pages. For that I navigated to the second page and inserted the header that I want. So far so good. The only problem is that if I don't have enough content to get to the second page I still have the blank second page with the header on it.
Is there a way to control this? Any useful trick to fix this?

**Comment by pensionarchitects-ben** [comment]
Are you converting to pdf/html or are you filling in a template? docx or odt?

**Comment by luisalves00** [comment]
I'm filling the template with velocity and then I convert odt to pdf.

**Comment by pensionarchitects-ben** [comment]
Can you set your document as attachment, or a test document which shows the same behaviour?

**Comment by luisalves00** [comment]
Here:
[medicalfile.zip](https://github.com/opensagres/xdocreport/files/302223/medicalfile.zip)

this is a strip of my original file.

**Comment by luisalves00** [comment]
I know I have it...is the way I get to the second page, so I can define the header there. 
An IF with what? I can check the size of the lists, but nothing guarantee me that the content will be only in the first page :(

**Comment by pensionarchitects-ben** [comment]
If its just for creating the header, you can use a pagebreak create the header on that next page. Then delete the pagebreak. The header is created and will normally not be deleted.

**Comment by luisalves00** [comment]
I found a solution, but it's blowing up with this exception:

java.lang.NullPointerException
	at fr.opensagres.xdocreport.document.docx.preprocessor.sax.RBufferedRegion.setTContent(RBufferedRegion.java:65)
	at fr.opensagres.xdocreport.document.docx.preprocessor.sax.PBufferedRegion.process(PBufferedRegion.java:216)
	at fr.opensagres.xdocreport.document.docx.preprocessor.sax.DocxBufferedDocument.onEndEndElement(DocxBufferedDocument.java:320)
	at fr.opensagres.xdocreport.document.preprocessor.sax.BufferedDocumentContentHandler.endElement(BufferedDocumentContentHandler.java:273)
	at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanEndElement(Unknown Source)


I've just used  { If {Page} > "1" " the content that I want to display "}  
This worked with a table with static text, but with MergeField seems to fail...

**Comment by luisalves00** [comment]
Is there any way to access the page number with velocity?

**Comment by angelozerr** [comment]
> I've just used { If {Page} > "1" " the content that I want to display "}

You cannot do that, because XDocReport doesn't evaluate MS Word expression.

> Is there any way to access the page number with velocity?

No, it's the same problem.



It's like HTML+Freemarker.

**Comment by luisalves00** [comment]
work: { If {Page} > "1" " static text...seems to work"}

fail: { If {Page} > "1" " «$velVariable»"} 

is not possible to make this work?

**Comment by luisalves00** [comment]
Instead of using a velocity variable, would something inside FieldsMetadata work?

**Comment by luisalves00** [comment]
My solution was to put 

{ If {Page} < "1" " page break"}  

so the page break is never rendered.
