### ISSUE TITLE
Check if list has at least one item causes an exception

### ISSUE THREAD

**Issue by luisalves00** [opensagres/xdocreport#136]
I'm trying to do:

#if($medications.size() > 0)
The list has items…	
#end

This work on other velocity templates that I have. But on a ODT template is causing this:

org.apache.velocity.exception.ParseErrorException: Lexical error,   Encountered: "g" (103), after : "&" at fr.opensagres.xdocreport.document.odt.ODTReport@71419cf7!content.xml[line 1, column 58592]
	at org.apache.velocity.Template.process(Template.java:151)
	at org.apache.velocity.runtime.resource.ResourceManagerImpl.loadResource(ResourceManagerImpl.java:437)
	at org.apache.velocity.runtime.resource.ResourceManagerImpl.getResource(ResourceManagerImpl.java:352)
	at org.apache.velocity.runtime.RuntimeInstance.getTemplate(RuntimeInstance.java:1533)
	at org.apache.velocity.app.VelocityEngine.getTemplate(VelocityEngine.java:392)
	at fr.opensagres.xdocreport.template.velocity.internal.VelocityTemplateEngine.processWithCache(VelocityTemplateEngine.java:97)
	at fr.opensagres.xdocreport.template.AbstractTemplateEngine.process(AbstractTemplateEngine.java:112)
	at fr.opensagres.xdocreport.template.AbstractTemplateEngine.process(AbstractTemplateEngine.java:83)
	at fr.opensagres.xdocreport.document.AbstractXDocReport.processTemplateEngine(AbstractXDocReport.java:775)
	at fr.opensagres.xdocreport.document.AbstractXDocReport.process(AbstractXDocReport.java:521)
	at fr.opensagres.xdocreport.document.AbstractXDocReport.process(AbstractXDocReport.java:487)
	at .......DocxReportsIceFormsTest.testPrintIceForm(DocxReportsIceFormsTest.java:108)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

Am I doing something wrong?

**Comment by angelozerr** [comment]
Do you use input field to set your velocity syntax? If no, you must use input field and not type directly your velocity directive in the odt.

**Comment by luisalves00** [comment]
I'm typing directly as I was using velocity over html file. 
What is an input field? Insert > Quick Parts> Field ? Can't find any Input Field...which one should O pick?

**Comment by luisalves00** [comment]
Tried with merged field. Now it doesn't give that exception anymore, but I cannot open the result file:

The ...odt cannot be opened because there are problems with the contents

Details:
An attribute value must not contain '<'.
Location: Part: /context.xml, Line 1, Column 60259

**Comment by pensionarchitects-ben** [comment]
In Libre/Open Office you set input fields by Insert > Fields > More Fields... > Functions > Input Field.

**Comment by luisalves00** [comment]
I'm using office. So I've used the merged field. Bu I get that error when opening the file. I'm going to try to use Libre Office to see if it has the same error.

**Comment by angelozerr** [comment]
@luisalves00 I suggest you really that you take time to read our wiki:

 * https://github.com/opensagres/xdocreport/wiki/ODTReportingJavaMain
 * and https://github.com/opensagres/xdocreport/wiki/ODTReportingQuickStart

The only problem with our wiki, that it was migrated from google project and there is some trouble with image and text. Any contribution are welcome to fix our wiki!

**Comment by angelozerr** [comment]
Please use MSOffice for docx and Libre/Open Office for ODT. If you ahve problem with docx, please attach your docx + Java main which works.

**Comment by luisalves00** [comment]
Doing on Libre, improves the result, but it still says that the file is corrupt, but if I say I want to recover it I can see the result.
I want to use DOCX, but when I use it my tables don't get populated and I'm not sure why.

**Comment by luisalves00** [comment]
this is my template:

[template.zip](https://github.com/opensagres/xdocreport/files/302567/template.zip)

as docx, nothing is replaced...and odt everything is replaced....I think on both I have problems with velocity expressions.

**Comment by luisalves00** [comment]
Update: it works if I use MergeField :)...now lemme try to use some velocity expressions.

**Comment by luisalves00** [comment]
Seems to work :)

Lessons learned:

- Always use field to have a consistent behaviour. (it's a bit boring but is doable)
- Don't use MS Office to edit ODT and vice-versa.

**Comment by angelozerr** [comment]
> Always use field to have a consistent behaviour. (it's a bit boring but is doable)

The problem when you don't use mergefield (or input field) is that MS Word or OpenOffice can split your velocity directive in several XML elements.

The first time when you save your docx, odt, you can have:

`${project}`

but if you update your docx (not necessary) the `${project}`, when you save, your expression can be splitted in several XML elements like

`<w:t>${p</wt><:t>roject}</w:t>`

and your template is broken (it was your case).

If you use mergefield, it doesn't split your content like this.

> Lessons learned:

Please take time to read wiki!

**Comment by luisalves00** [comment]
Point taken. As a suggestion, highlight this part (not sure if there's a fancy component for that):

"For the field to replace $project.Name, it is advice to use Input-Field and not to type directly $project.Name in your documentation (TODO : explain why)."

And it seems that "advice" is not a good word, and you already gave me the explanation why.

No I have a weird issue...I'm getting this on a column of a table:

$item_diseases.AditionalInfo

it's fed by this:

this.description = description == null ? "" : description;

If the description is filled then it works okay, but if null or empty I get that $item_diseases.AditionalInfo.

**Comment by luisalves00** [comment]
Also if the content of the cell is too large the cell is not expanding, making part of the text not visible...is there a solution for this?

**Comment by luisalves00** [comment]
Forget it...I was doing the null check for the description and not for the additional info.

this.aditionalInfo = aditionalInfo == null ? "" : aditionalInfo;

the alignment is also fixed...it's just a word config.
