### ISSUE TITLE
hyperlink insert issue

### ISSUE THREAD

**Issue by creepid** [opensagres/xdocreport#15]
Hello!

I used the first example in the article https://code.google.com/p/xdocreport/wiki/DocxReportingJavaMain, so i opened DocxProjectWithVelocity.docx file, selected field «$project.Name» in template and inserted some hyperlink (ex: http://google.com), 

![hyperlink_exception](https://cloud.githubusercontent.com/assets/4024331/6271691/713d3852-b873-11e4-9cbd-37ca6dc85392.PNG)

when the exception described below occured. What i did wrong?

Thanks

Exception in thread "main" java.lang.NullPointerException
	at fr.opensagres.xdocreport.document.docx.preprocessor.sax.RBufferedRegion.getTContent(RBufferedRegion.java:95)
	at fr.opensagres.xdocreport.document.docx.preprocessor.sax.hyperlinks.HyperlinkBufferedRegion.getAllTContent(HyperlinkBufferedRegion.java:189)
	at fr.opensagres.xdocreport.document.docx.preprocessor.sax.hyperlinks.HyperlinkBufferedRegion.process(HyperlinkBufferedRegion.java:100)
	at fr.opensagres.xdocreport.document.docx.preprocessor.sax.DocxBufferedDocument.onEndEndElement(DocxBufferedDocument.java:359)
	at fr.opensagres.xdocreport.document.preprocessor.sax.BufferedDocumentContentHandler.endElement(BufferedDocumentContentHandler.java:273)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:609)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1781)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2957)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at fr.opensagres.xdocreport.document.preprocessor.sax.SAXXDocPreprocessor.preprocess(SAXXDocPreprocessor.java:62)
	at fr.opensagres.xdocreport.document.preprocessor.sax.SAXXDocPreprocessor.preprocess(SAXXDocPreprocessor.java:47)
	at fr.opensagres.xdocreport.document.preprocessor.AbstractXDocPreprocessor.preprocess(AbstractXDocPreprocessor.java:88)
	at fr.opensagres.xdocreport.document.AbstractXDocReport.doPreprocessorIfNeeded(AbstractXDocReport.java:366)
	at fr.opensagres.xdocreport.document.AbstractXDocReport.process(AbstractXDocReport.java:512)
	at fr.opensagres.xdocreport.document.AbstractXDocReport.process(AbstractXDocReport.java:487)
	at xdocreporttest.XDocReportTest.main(XDocReportTest.java:47)

**Comment by angelozerr** [comment]
Which version of XDocReport do you use (last is 1.0.5)

Which MS Word version do you use?

Perhaps it's an hyperlink format that XDocReport doesn't support? Please attach your docx (with github it's not possible) so I suggest you to create a simple github project with your docx + Java code).

I will study the problem when I will have time.

Thanks

**Comment by creepid** [comment]
I used 2010 MS Word version, here is example project: https://github.com/creepid/XDocReport-link-issue

**Comment by angelozerr** [comment]
Your docx contains a complex hyperlink that XDocReport seems not supporting : 

In your case there are hyperlink and mergefield : 

```xml
<w:hyperlink w:history="1" r:id="rId7">
  <w:r w:rsidR="00EA33F7" w:rsidRPr="00EA33F7">
    <w:rPr>
      <w:rStyle w:val="Lienhypertexte" />
    </w:rPr>
    <w:fldChar w:fldCharType="begin" />
  </w:r>
  <w:r w:rsidR="00EA33F7" w:rsidRPr="00EA33F7">
    <w:rPr>
      <w:rStyle w:val="Lienhypertexte" />
    </w:rPr>
    <w:instrText xml:space="preserve"> MERGEFIELD $project.Link \* MERGEFORMAT </w:instrText>
  </w:r>
  <w:r w:rsidR="00EA33F7" w:rsidRPr="00EA33F7">
    <w:rPr>
      <w:rStyle w:val="Lienhypertexte" />
    </w:rPr>
    <w:fldChar w:fldCharType="separate" />
  </w:r>
  <w:r w:rsidR="00CE1B87">
    <w:rPr>
      <w:rStyle w:val="Lienhypertexte" />
      <w:noProof />
    </w:rPr>
    <w:t>«$project.Link»</w:t>
  </w:r>
  <w:r w:rsidR="00EA33F7" w:rsidRPr="00EA33F7">
    <w:rPr>
      <w:rStyle w:val="Lienhypertexte" />
      <w:noProof />
    </w:rPr>
    <w:fldChar w:fldCharType="end" />
  </w:r>
</w:hyperlink>
```

although XDocReport waits this syntax : 

```xml
<w:hyperlink w:history="1" r:id="rId6">
  <w:r w:rsidR="001C41B9" w:rsidRPr="001C41B9">
    <w:rPr>
      <w:rStyle w:val="Lienhypertexte" />
    </w:rPr>
    <w:t>$project.Link</w:t>
  </w:r>
</w:hyperlink>
```

I don't know why you have this syntax. Not time today to support it.
