### ISSUE TITLE
Use one template for a list of object

### ISSUE THREAD

**Issue by igomon** [opensagres/xdocreport#171]
Hello,
I have a  list called users like this:

List<User> users = new ArrayList<User>();
I get it from a db.

Is it possible to use it( maybe not using a List) to have a report for each user starting from a single template?

I tried something like this
```javascript
InputStream in = new FileInputStream(absoluteDiskPath+"/"+idReport);
IXDocReport report = XDocReportRegistry.getRegistry().loadReport(in,TemplateEngineKind.Velocity);
IContext context = report.createContext();
		        	
List<User> users = new ArrayList<User>();
for (int i=0;i<idsArray.length;i++){
    User u =  DAO.getInstance().getUserForReportById(Integer.parseInt(idsArray[i]));
    users.add(u);
}  		
        	
context.put("users", users);
```
and in the template I used the foreach loop as shown in
http://people.apache.org/~henning/velocity/html/ch05s04.html

But I retrieve the following error
```javascript
org.apache.velocity.exception.ParseErrorException: Invalid arg #0 in directive #foreach at fr.opensagres.xdocreport.document.odt.ODTReport@1f250ac!content.xml[line 1, column 29240]

	at org.apache.velocity.Template.process(Template.java:151)
	at org.apache.velocity.runtime.resource.ResourceManagerImpl.loadResource(ResourceManagerImpl.java:437)
	at org.apache.velocity.runtime.resource.ResourceManagerImpl.getResource(ResourceManagerImpl.java:352)
	at org.apache.velocity.runtime.RuntimeInstance.getTemplate(RuntimeInstance.java:1533)
	at org.apache.velocity.app.VelocityEngine.getTemplate(VelocityEngine.java:392)
	at fr.opensagres.xdocreport.template.velocity.internal.VelocityTemplateEngine.processWithCache(VelocityTemplateEngine.java:97)
	at fr.opensagres.xdocreport.template.AbstractTemplateEngine.process(AbstractTemplateEngine.java:111)
	at fr.opensagres.xdocreport.template.AbstractTemplateEngine.process(AbstractTemplateEngine.java:83)
	at fr.opensagres.xdocreport.document.AbstractXDocReport.processTemplateEngine(AbstractXDocReport.java:775)
	at fr.opensagres.xdocreport.document.AbstractXDocReport.process(AbstractXDocReport.java:521)
	at fr.opensagres.xdocreport.document.AbstractXDocReport.process(AbstractXDocReport.java:487)
	at it.marionegri.gp.webapp.servlet.DoReportMassivo.doPost(DoReportMassivo.java:90)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:647)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1008)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:312)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
```

Thank you for any suggestion.

**Comment by pensionarchitects-ben** [comment]
Can you attach a example template.

**Comment by igomon** [comment]
Sure, sorry.

The original file is an odt file 
[2.pdf](https://github.com/opensagres/xdocreport/files/555157/2.pdf)

I also tried the template without using the foreach loop, and passing just one object to the context.put("user", user) method and it works perfectly.

**Comment by angelozerr** [comment]
Please check:

1) you are using input text field (for odt) and merge field (for docx) to write your Velocity code
2) uses a valid Velocity syntax. It seems that you are writing:

`#foreach(user in users)`

Although it should be:

`#foreach($user in $users)`

Please take time to read https://github.com/opensagres/xdocreport/wiki/ODTReportingJavaMainListField (and update the wiki if needed)
