### ISSUE TITLE
ODF table row loop issues - element type "text:p" must be terminated by the matching end-tag

### ISSUE THREAD

**Issue by mgilbertnz** [opensagres/xdocreport#176]
Hi there,

We've been using ODF -> PDF conversion for generating one of our timesheet reports.

When developing this report, several times I've managed to get myself in a state where the report works correctly however if I open the ODF document in Open Office or Libre Office and hit save (with no changes), it re-formats the source XML significantly and then the following error occurs: 

`[error] o.o.o.p.OdfPackageDocument - null
org.xml.sax.SAXParseException: The element type "text:p" must be terminated by the matching end-tag "</text:p>".
        at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:na]
        at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:na]
        at org.odftoolkit.odfdom.pkg.OdfFileDom.initialize(OdfFileDom.java:142) [odfdom-java-0.8.7.jar:na]
        at org.odftoolkit.odfdom.dom.OdfContentDom.initialize(OdfContentDom.java:55) [odfdom-java-0.8.7.jar:na]
        at org.odftoolkit.odfdom.pkg.OdfFileDom.<init>(OdfFileDom.java:87) [odfdom-java-0.8.7.jar:na]
        at org.odftoolkit.odfdom.dom.OdfContentDom.<init>(OdfContentDom.java:45) [odfdom-java-0.8.7.jar:na]
        at org.odftoolkit.odfdom.pkg.OdfFileDom.newFileDom(OdfFileDom.java:110) [odfdom-java-0.8.7.jar:na]
        at org.odftoolkit.odfdom.pkg.OdfPackageDocument.getFileDom(OdfPackageDocument.java:281) [odfdom-java-0.8.7.jar:na]
        at org.odftoolkit.odfdom.dom.OdfSchemaDocument.getFileDom(OdfSchemaDocument.java:312) [odfdom-java-0.8.7.jar:na]
        at org.odftoolkit.odfdom.dom.OdfSchemaDocument.getContentDom(OdfSchemaDocument.java:190) [odfdom-java-0.8.7.jar:na]
        at org.odftoolkit.odfdom.converter.pdf.PdfConverter.processStyles(PdfConverter.java:103) [org.odftoolkit.odfdom.converter.pdf-1.0.6.jar:1.0.6]
        at org.odftoolkit.odfdom.converter.pdf.PdfConverter.doConvert(PdfConverter.java:61) [org.odftoolkit.odfdom.converter.pdf-1.0.6.jar:1.0.6]
        at org.odftoolkit.odfdom.converter.pdf.PdfConverter.doConvert(PdfConverter.java:43) [org.odftoolkit.odfdom.converter.pdf-1.0.6.jar:1.0.6]
        at org.odftoolkit.odfdom.converter.core.AbstractODFConverter.convert(AbstractODFConverter.java:42) [org.odftoolkit.odfdom.converter.core-1.0.6.jar:1.0.6]
        at fr.opensagres.xdocreport.converter.odt.odfdom.itext.ODF2PDFViaITextConverter.convert(ODF2PDFViaITextConverter.java:62) [fr.opensagres.xdocreport.converter.odt.odfdom-1.0.6.jar:1.0.6]
        at fr.opensagres.xdocreport.document.AbstractXDocReport.convert(AbstractXDocReport.java:713) [fr.opensagres.xdocreport.document-1.0.6.jar:1.0.6]
`

I suspect this comes from the fact that I'm looping over an array to add rows to a table.  It looks like the resulting document has an uneven number of <text:p></text:p> tags.

Here are my example templates and resulting reports, the difference between template-correct.odt and template-incorrect.odt is me opening it in Libre Office 5.1.4.2 and hitting save.  Report-correct.pdf and report-incorrect.pdf are generated with the same dataset.

[templates-and-reports.zip](https://github.com/opensagres/xdocreport/files/638094/templates-and-reports.zip)

Has anyone encountered a similar issue?  As a workaround I can copy + paste all of the template apart from the table loop section to a new document and re-author the table loop section from scratch.  This works for a while but after a few saves the issue seems to reappear.  It's not a long term solution.

Apologies if this question belongs in a Libre Office forum.  I might post it there now as well.

**Comment by pensionarchitects-ben** [comment]
it is probably the if not the loop. This is a problem I most often see when a span object is created over one of my freemarker/velocity fields. This happens mostly because of styles differences on the fields. Maybe search along those lines.

**Comment by mgilbertnz** [comment]
Thanks!  I'll investigate.

**Comment by rafaelduqueestrada** [comment]
Hi,
I don't know if it is the same problem:
My client has reported a bug today and the stack in the logfile was:
"2017-01-12 17:09:23 ERROR [fr.opensagres.xdocreport.document.textstyling.AbstractTextStylingTransformer] - The element type "p" must be terminated by the matching end-tag "</p>".
"
After 1 hour analising the data, I realized that the user used TAB when input the information in the form. When I removed the TAB in the database the problem was solved.

**Comment by shivajain** [comment]
I am also struggeling with the same issue, just wondering if this problem has got any proper solution.
`INFO: None-ODF attribute created for loext:mime-type
[Fatal Error] :1:23214: The element type "text:p" must be terminated by the matching end-tag "</text:p>".
Jun 12, 2018 9:02:04 AM org.odftoolkit.odfdom.pkg.OdfFileDom initialize
SEVERE: null
org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 23214; The element type "text:p" must be terminated by the matching end-tag "</text:p>".
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.odftoolkit.odfdom.pkg.OdfFileDom.initialize(OdfFileDom.java:142)
	at org.odftoolkit.odfdom.dom.OdfContentDom.initialize(OdfContentDom.java:55)
	at org.odftoolkit.odfdom.pkg.OdfFileDom.<init>(OdfFileDom.java:87)
	at org.odftoolkit.odfdom.dom.OdfContentDom.<init>(OdfContentDom.java:45)
	at org.odftoolkit.odfdom.pkg.OdfFileDom.newFileDom(OdfFileDom.java:110)
	at org.odftoolkit.odfdom.pkg.OdfPackageDocument.getFileDom(OdfPackageDocument.java:281)
	at org.odftoolkit.odfdom.dom.OdfSchemaDocument.getFileDom(OdfSchemaDocument.java:312)`

**Comment by TinusJ** [comment]
2018-11-07 09:30:00.691 I:i-DOCS TEST U:admin@picksmart.co.za ERROR org.odftoolkit.odfdom.pkg.OdfPackageDocument - null
org.xml.sax.SAXParseException: The element type "text:p" must be terminated by the matching end-tag "</text:p>".
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.odftoolkit.odfdom.pkg.OdfFileDom.initialize(OdfFileDom.java:142)
	at org.odftoolkit.odfdom.dom.OdfContentDom.initialize(OdfContentDom.java:55)
	at org.odftoolkit.odfdom.pkg.OdfFileDom.<init>(OdfFileDom.java:87)
	at org.odftoolkit.odfdom.dom.OdfContentDom.<init>(OdfContentDom.java:45)
	at org.odftoolkit.odfdom.pkg.OdfFileDom.newFileDom(OdfFileDom.java:110)
	at org.odftoolkit.odfdom.pkg.OdfPackageDocument.getFileDom(OdfPackageDocument.java:281)
	at org.odftoolkit.odfdom.dom.OdfSchemaDocument.getFileDom(OdfSchemaDocument.java:312)
	at org.odftoolkit.odfdom.dom.OdfSchemaDocument.getContentDom(OdfSchemaDocument.java:190)
	at fr.opensagres.odfdom.converter.pdf.PdfConverter.processStyles(PdfConverter.java:104)
	at fr.opensagres.odfdom.converter.pdf.PdfConverter.doConvert(PdfConverter.java:62)
	at fr.opensagres.odfdom.converter.pdf.PdfConverter.doConvert(PdfConverter.java:44)
	at fr.opensagres.odfdom.converter.core.AbstractODFConverter.convert(AbstractODFConverter.java:42)
	at fr.opensagres.xdocreport.converter.odt.odfdom.itext.ODF2PDFViaITextConverter.convert(ODF2PDFViaITextConverter.java:62)
	at fr.opensagres.xdocreport.document.AbstractXDocReport.convert(AbstractXDocReport.java:713)

**Comment by TinusJ** [comment]
Any news on this?
