### ISSUE TITLE
InputStream cannot be null for DocxProject to PDF

### ISSUE THREAD

**Issue by saru17** [opensagres/xdocreport#180]
Hi,

I am trying to DocxProjectWithVelocityList2PDF.java, i am getting the below excpetion

java.io.IOException: InputStream cannot be null.
	at fr.opensagres.xdocreport.core.io.XDocArchive.readZip(XDocArchive.java:289)
	at fr.opensagres.xdocreport.document.registry.XDocReportRegistry.createReport(XDocReportRegistry.java:359)
	at fr.opensagres.xdocreport.document.registry.XDocReportRegistry.loadReport(XDocReportRegistry.java:326)
	at fr.opensagres.xdocreport.document.registry.XDocReportRegistry.loadReport(XDocReportRegistry.java:317)
	at fr.opensagres.xdocreport.document.registry.XDocReportRegistry.loadReport(XDocReportRegistry.java:302)
	at fr.opensagres.xdocreport.samples.docxandvelocity.DocxProjectWithVelocityList2PDF.main(DocxProjectWithVelocityList2PDF.java:204)

**Comment by angelozerr** [comment]
I think you have not imported correctly the project. You error means that the docx inputstream is not in your classpath.
