### ISSUE TITLE
NumberFormatException Whren replacing Image in ODT file using Velocity

### ISSUE THREAD

**Issue by SuperPat45** [opensagres/xdocreport#187]
Hi,

Since I migrate from XDocReport 1.0.4 to 2.0.0, I was unable to replace an Image in an ODT file using Velocity.

I have the exception:
```
org.apache.velocity.exception.MethodInvocationException: Invocation of method 'getWidth' in  class fr.opensagres.xdocreport.document.odt.images.ODTImageRegistry threw exception java.lang.NumberFormatException: For input string: "0.582cm" at fr.opensagres.xdocreport.document.odt.ODTReport@1aec4f!content.xml[line 1, column 4094]
	at org.apache.velocity.runtime.parser.node.ASTMethod.handleInvocationException(ASTMethod.java:243)
	at org.apache.velocity.runtime.parser.node.ASTMethod.execute(ASTMethod.java:187)
	at org.apache.velocity.runtime.parser.node.ASTReference.execute(ASTReference.java:280)
	at org.apache.velocity.runtime.parser.node.ASTReference.render(ASTReference.java:369)
	at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:72)
	at org.apache.velocity.runtime.parser.node.ASTIfStatement.render(ASTIfStatement.java:87)
	at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:342)
	at org.apache.velocity.runtime.RuntimeInstance.render(RuntimeInstance.java:1378)
	at org.apache.velocity.runtime.RuntimeInstance.evaluate(RuntimeInstance.java:1314)
	at org.apache.velocity.app.VelocityEngine.evaluate(VelocityEngine.java:272)
	at fr.opensagres.xdocreport.template.velocity.internal.VelocityTemplateEngine.processNoCache(VelocityTemplateEngine.java:109)
	at fr.opensagres.xdocreport.template.AbstractTemplateEngine.process(AbstractTemplateEngine.java:118)
	at fr.opensagres.xdocreport.template.AbstractTemplateEngine.process(AbstractTemplateEngine.java:83)
	at fr.opensagres.xdocreport.document.AbstractXDocReport.processTemplateEngine(AbstractXDocReport.java:775)
	at fr.opensagres.xdocreport.document.AbstractXDocReport.process(AbstractXDocReport.java:521)
	at fr.opensagres.xdocreport.document.AbstractXDocReport.process(AbstractXDocReport.java:487)
	...
Caused by: java.lang.NumberFormatException: For input string: "0.582cm"
	at sun.misc.FloatingDecimal.readJavaFormatString(Unknown Source)
	at sun.misc.FloatingDecimal.parseFloat(Unknown Source)
	at java.lang.Float.parseFloat(Unknown Source)
	at fr.opensagres.xdocreport.document.odt.images.ODTImageRegistry.getSize(ODTImageRegistry.java:81)
	at fr.opensagres.xdocreport.document.images.AbstractImageRegistry.getWidth(AbstractImageRegistry.java:266)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.doInvoke(UberspectImpl.java:395)
	at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.invoke(UberspectImpl.java:384)
	at org.apache.velocity.runtime.parser.node.ASTMethod.execute(ASTMethod.java:173)
	... 162 more
```
It seem that the "defaultWidth" in the AbstractImageRegistery.getWidth() method has a "cm" unite and XdocReport don't like this...

For example with this simple ODT file created with LibreOffice :
[bug.zip](https://github.com/opensagres/xdocreport/files/794385/bug.zip)

**Comment by angelozerr** [comment]
@arons is it possible to see this problem please? It seems the problem comes from https://github.com/opensagres/xdocreport/commit/60be8a55c91c39ca50f0b785ffc4f5afc60b06bc#diff-ef333f1c6a097343108501cb13271d11L65

It should be very cool to fix this problem and add tests. Thanks!

**Comment by arons** [comment]
Sure I'll check it

**Comment by angelozerr** [comment]
Thanks!

**Comment by arons** [comment]
problem should be solved, anyway the correct size can be computed.
I currently don't know how to covert from cm to pixel for ODT.

**Comment by SuperPat45** [comment]
Thanks

**Comment by deso82** [comment]
Hello I have the same issue when replacing Image in ODT file using Freemarker.
But in my case it seems that the metrics is: inches not cm.

0    [main] ERROR (runtime.java:98) Error executing FreeMarker template
FreeMarker template error:
Method "public java.lang.String fr.opensagres.xdocreport.document.images.AbstractImageRegistry.getWidth(fr.opensagres.xdocreport.document.images.ImageProviderInfo,java.lang.String) throws java.io.IOException" threw an exception
 when invoked on fr.opensagres.xdocreport.document.odt.images.ODTImageRegistry object "fr.opensagres.xdocreport.document.odt.images.ODTImageRegistry@2f3565c0". See cause exception.

The failing instruction (FTL stack trace):
----------
==> ${___ImageRegistry.getWidth(___imageI...  [in template "fr.opensagres.xdocreport.document.odt.ODTReport@18e4674d!styles.xml" at line 4, column 19265]
----------

Java stack trace (for programmers):
----------
freemarker.template.TemplateModelException: [... Exception message was already printed; see it above ...]
        at freemarker.ext.beans.SimpleMethodModel.exec(SimpleMethodModel.java:135)
        at freemarker.core.MethodCall._eval(MethodCall.java:98)
        at freemarker.core.Expression.eval(Expression.java:111)
        at freemarker.core.Expression.evalAndCoerceToString(Expression.java:115)
        at freemarker.core.StringBuiltins$StringBuiltIn._eval(StringBuiltins.java:87)
        at freemarker.core.Expression.eval(Expression.java:111)
        at freemarker.core.Expression.evalAndCoerceToString(Expression.java:115)
        at freemarker.core.StringBuiltins$StringBuiltIn._eval(StringBuiltins.java:87)
        at freemarker.core.Expression.eval(Expression.java:111)
        at freemarker.core.MethodCall._eval(MethodCall.java:91)
        at freemarker.core.Expression.eval(Expression.java:111)
        at freemarker.core.Expression.evalAndCoerceToString(Expression.java:115)
        at freemarker.core.StringBuiltins$StringBuiltIn._eval(StringBuiltins.java:87)
        at freemarker.core.Expression.eval(Expression.java:111)
        at freemarker.core.MethodCall._eval(MethodCall.java:91)
        at freemarker.core.Expression.eval(Expression.java:111)
        at freemarker.core.Expression.evalAndCoerceToString(Expression.java:115)
        at freemarker.core.StringBuiltins$StringBuiltIn._eval(StringBuiltins.java:87)
        at freemarker.core.Expression.eval(Expression.java:111)
        at freemarker.core.MethodCall._eval(MethodCall.java:91)
        at freemarker.core.Expression.eval(Expression.java:111)
        at freemarker.core.Expression.evalAndCoerceToString(Expression.java:115)
        at freemarker.core.DollarVariable.accept(DollarVariable.java:76)
        at freemarker.core.Environment.visit(Environment.java:265)
        at freemarker.core.MixedContent.accept(MixedContent.java:93)
        at freemarker.core.Environment.visitByHiddingParent(Environment.java:286)
        at freemarker.core.ConditionalBlock.accept(ConditionalBlock.java:86)
        at freemarker.core.Environment.visit(Environment.java:265)
        at freemarker.core.MixedContent.accept(MixedContent.java:93)
        at freemarker.core.Environment.visit(Environment.java:265)
        at freemarker.core.EscapeBlock.accept(EscapeBlock.java:85)
        at freemarker.core.Environment.visit(Environment.java:265)
        at freemarker.core.MixedContent.accept(MixedContent.java:93)
        at freemarker.core.Environment.visit(Environment.java:265)
        at freemarker.core.Environment.process(Environment.java:243)
        at fr.opensagres.xdocreport.template.freemarker.FreemarkerTemplateEngine.process(FreemarkerTemplateEngine.java:163)
        at fr.opensagres.xdocreport.template.freemarker.FreemarkerTemplateEngine.processWithCache(FreemarkerTemplateEngine.java:112)
        at fr.opensagres.xdocreport.template.AbstractTemplateEngine.process(AbstractTemplateEngine.java:112)
        at fr.opensagres.xdocreport.template.AbstractTemplateEngine.process(AbstractTemplateEngine.java:83)
        at fr.opensagres.xdocreport.document.AbstractXDocReport.processTemplateEngine(AbstractXDocReport.java:775)
        at fr.opensagres.xdocreport.document.AbstractXDocReport.process(AbstractXDocReport.java:521)
        at fr.opensagres.xdocreport.document.AbstractXDocReport.process(AbstractXDocReport.java:487)
        at com.gemalto.ics.rnd.pm.ri.productionreports.odt.generators.GeneratorOdt.fillDataToReport(GeneratorOdt.java:149)
        at com.gemalto.ics.rnd.pm.ri.productionreports.odt.generators.GeneratorOdt.lambda$reportProcessor$0(GeneratorOdt.java:102)
        at java.util.ArrayList.forEach(ArrayList.java:1249)
        at com.gemalto.ics.rnd.pm.ri.productionreports.odt.generators.GeneratorOdt.reportProcessor(GeneratorOdt.java:100)
        at com.gemalto.ics.rnd.pm.ri.productionreports.odt.generators.GeneratorOdt.generate(GeneratorOdt.java:74)
        at com.gemalto.ics.rnd.pm.ri.productionreports.odt.generators.GeneratorOdtTest.generateOdtTest(GeneratorOdtTest.java:174)
        at com.gemalto.ics.rnd.pm.ri.productionreports.odt.generators.GeneratorOdtTest.testReportBatchContent(GeneratorOdtTest.java:96)
        at com.gemalto.ics.rnd.pm.ri.productionreports.odt.generators.GeneratorOdtTest.batchContentReport(GeneratorOdtTest.java:38)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: java.lang.NumberFormatException: For input string: "**2.5835in**"
        at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
        at sun.misc.FloatingDecimal.parseFloat(FloatingDecimal.java:122)
        at java.lang.Float.parseFloat(Float.java:451)
        at fr.opensagres.xdocreport.document.odt.images.ODTImageRegistry.getSize(ODTImageRegistry.java:81)
        at fr.opensagres.xdocreport.document.images.AbstractImageRegistry.getWidth(AbstractImageRegistry.java:266)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at freemarker.ext.beans.BeansWrapper.invokeMethod(BeansWrapper.java:912)
        at freemarker.ext.beans.SimpleMethodModel.exec(SimpleMethodModel.java:107)
        ... 78 more

**Comment by pensionarchitects-ben** [comment]
Stay in XDocReport 1.0.6 or go to 2.0.1-SNAPSHOT, and it's fixed
