### ISSUE TITLE
Set template engine with IXDocReport#setTemplateEngine

### ISSUE THREAD

**Issue by djwalid** [opensagres/xdocreport#233]
Hi,
i am using xdocreport.
i'm getting the following exception : 
Null template engine. Set template engine with IXDocReport#setTemplateEngine.
fr.opensagres.xdocreport.core.XDocReportException: Null template engine. Set template engine with IXDocReport#setTemplateEngine.
	at fr.opensagres.xdocreport.document.AbstractXDocReport.internalGetTemplateEngine(AbstractXDocReport.java:866)
	at fr.opensagres.xdocreport.document.AbstractXDocReport.createContext(AbstractXDocReport.java:462)
	at sga.api.report.ppo.web.AbstractprocessXDocReportServlet2.doGenerateReport(AbstractprocessXDocReportServlet2.java:234)
	at sga.api.report.ppo.web.AbstractprocessXDocReportServlet2.processRequest(AbstractprocessXDocReportServlet2.java:97)
	at fr.opensagres.xdocreport.document.web.BaseXDocReportServlet.doGet(BaseXDocReportServlet.java:78)

i attached to this issue pom.xml, atlassian-plugin.xml, and my java servlet.
i don't know the origin of this exception. can anyone help me. 
Thank's

[github.zip](https://github.com/opensagres/xdocreport/files/1221635/github.zip)

**Comment by angelozerr** [comment]
Hav you velocity and their dependencies in your classpath?

**Comment by djwalid** [comment]
Hi,
i'm using atlassian SDK to create a jira plugin, i used atlas-create-jira-plugin to create the plugin and no .classpath was generated.
i don't know how to fixe that.
Merci d'avance :)

**Comment by djwalid** [comment]
Since it's a maven project i added the following dependencies in the pom: 
 <dependency>
            <groupId>fr.opensagres.xdocreport</groupId>
            <artifactId>fr.opensagres.xdocreport.document.docx</artifactId>
            <version>1.0.5</version>
            <scope>compile</scope>
        </dependency>     
        <dependency>
            <groupId>fr.opensagres.xdocreport</groupId>
            <artifactId>fr.opensagres.xdocreport.template.velocity</artifactId>
            <version>1.0.5</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>fr.opensagres.xdocreport</groupId>
            <artifactId>fr.opensagres.xdocreport.template.freemarker</artifactId>
            <version>1.0.5</version>
            <scope>compile</scope>
        </dependency>
and it doesn't work.

**Comment by djwalid** [comment]
Any pointer will be helpful.

**Comment by djwalid** [comment]
Hi,

I have finally found the solution, I had to use the following dependency :

```
<dependency>
            <groupId>fr.opensagres.xdocreport</groupId>
            <artifactId>xdocreport</artifactId>
            <version>1.0.4</version>
            <scope>compile</scope>
</dependency>
```

Thanks for your help
Best regards,
