### ISSUE TITLE
XDocReportRegistry thread safety

### ISSUE THREAD

**Issue by fanfy** [opensagres/xdocreport#234]
Hi,

I've encountered an exception when rendering .odt reports: 

`java.util.ConcurrentModificationException: null
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at fr.opensagres.xdocreport.document.registry.XDocReportRegistry.createReport(XDocReportRegistry.java:366)
	at fr.opensagres.xdocreport.document.registry.XDocReportRegistry.createReport(XDocReportRegistry.java:359)
	at fr.opensagres.xdocreport.document.registry.XDocReportRegistry.loadReport(XDocReportRegistry.java:325)
	at fr.opensagres.xdocreport.document.registry.XDocReportRegistry.loadReport(XDocReportRegistry.java:316)
	at fr.opensagres.xdocreport.document.registry.XDocReportRegistry.loadReport(XDocReportRegistry.java:301)....`

I think the problem is that the XDocReportRegistry singleton is not initialized and the method initializedIfNeeded is not thread safe. As a workaround I now call XDocReportRegistry.getRegistry().initialize() at application start up.

**Comment by angelozerr** [comment]
Any PR are welcome, thanks!
