### ISSUE TITLE
Samples are not working

### ISSUE THREAD

**Issue by Rapster** [opensagres/xdocreport#242]
I post this issue in this repo since I tried with a "from scratch" project and got the same exception (this is why i think it's a general problem and not related to the samples). Basically, I want to use a docx template (using Freemarker) and convert it to PDF, but I end up with this exception:
```
java.lang.NoClassDefFoundError: freemarker/template/TemplateException
	at fr.opensagres.xdocreport.template.freemarker.discovery.FreemarkerTemplateEngineDiscovery.createTemplateEngine(FreemarkerTemplateEngineDiscovery.java:42)
	at fr.opensagres.xdocreport.template.registry.TemplateEngineRegistry.registerInstance(TemplateEngineRegistry.java:78)
	at fr.opensagres.xdocreport.template.registry.TemplateEngineRegistry.registerInstance(TemplateEngineRegistry.java:42)
	at fr.opensagres.xdocreport.core.registry.AbstractRegistry.initializeIfNeeded(AbstractRegistry.java:76)
	at fr.opensagres.xdocreport.template.registry.TemplateEngineRegistry.getTemplateEngineKinds(TemplateEngineRegistry.java:118)
	at fr.opensagres.xdocreport.document.registry.TemplateEngineInitializerRegistry.onEndInitialization(TemplateEngineInitializerRegistry.java:166)
	at fr.opensagres.xdocreport.core.registry.AbstractRegistry.initializeIfNeeded(AbstractRegistry.java:87)
	at fr.opensagres.xdocreport.document.registry.TemplateEngineInitializerRegistry.getTemplateEngine(TemplateEngineInitializerRegistry.java:84)
	at fr.opensagres.xdocreport.document.registry.XDocReportRegistry.loadReport(XDocReportRegistry.java:338)
	at fr.opensagres.xdocreport.document.registry.XDocReportRegistry.loadReport(XDocReportRegistry.java:316)
	at fr.opensagres.xdocreport.document.registry.XDocReportRegistry.loadReport(XDocReportRegistry.java:301)
	at fr.opensagres.xdocreport.samples.docxandfreemarker.DocxProjectWithFreemarker.main(DocxProjectWithFreemarker.java:191)
Caused by: java.lang.ClassNotFoundException: freemarker.template.TemplateException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 12 more
```
you can reproduce this issue running `DocxProjectWithVelocityList2PDF.java` from `xdocreport.samples\samples\fr.opensagres.xdocreport.samples.docxandfreemarker`

I quickly tried `DocxProjectWithVelocityList2PDF` from the same project and got thi exception:
```
fr.opensagres.xdocreport.converter.XDocConverterException: java.lang.NoClassDefFoundError: com/itextpdf/text/pdf/PdfAWriter
	at fr.opensagres.xdocreport.document.AbstractXDocReport.convert(AbstractXDocReport.java:748)
	at fr.opensagres.xdocreport.samples.docxandvelocity.DocxProjectWithVelocityList2PDF.main(DocxProjectWithVelocityList2PDF.java:276)
Caused by: java.lang.NoClassDefFoundError: com/itextpdf/text/pdf/PdfAWriter
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at fr.opensagres.poi.xwpf.converter.pdf.internal.PdfMapper.startVisitDocument(PdfMapper.java:149)
	at fr.opensagres.poi.xwpf.converter.pdf.internal.PdfMapper.startVisitDocument(PdfMapper.java:101)
	at fr.opensagres.poi.xwpf.converter.core.XWPFDocumentVisitor.start(XWPFDocumentVisitor.java:180)
	at fr.opensagres.poi.xwpf.converter.pdf.PdfConverter.doConvert(PdfConverter.java:58)
	at fr.opensagres.poi.xwpf.converter.pdf.PdfConverter.doConvert(PdfConverter.java:40)
	at fr.opensagres.poi.xwpf.converter.core.AbstractXWPFConverter.convert(AbstractXWPFConverter.java:46)
	at fr.opensagres.xdocreport.converter.docx.poi.itext.XWPF2PDFViaITextConverter.convert(XWPF2PDFViaITextConverter.java:67)
	at fr.opensagres.xdocreport.document.AbstractXDocReport.convert(AbstractXDocReport.java:713)
	... 1 more
Caused by: java.lang.ClassNotFoundException: com.itextpdf.text.pdf.PdfAWriter
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
```

**Comment by angelozerr** [comment]
Have you Freemarker and iText in your classpath?

**Comment by Rapster** [comment]
Yes

**Comment by Rapster** [comment]
I run the samples with xdocreport 2.0.1 FYI

**Comment by angelozerr** [comment]
Do you use the same Freemarker version than pom?

**Comment by Rapster** [comment]
freemarker is a transitive dependency pulled by `fr.opensagres.xdocreport.template.freemarker` with compile scope so I don't have to specify the version

**Comment by angelozerr** [comment]
I suggest you that you create in your project a sample with Freemarker like http://freemarker.org/docs/pgui_quickstart_all.html to check if Freemarker is available.

**Comment by Rapster** [comment]
The problem was caused due to a bad downloading of the jar by maven... I just had to clear the local cache :wink: Thanks for the quick answers

**Comment by angelozerr** [comment]
Glad it works for you.
