### ISSUE TITLE
NullPointerException Error converting .odt to .pdf

### ISSUE THREAD

**Issue by KimHyeockJin** [opensagres/xdocreport#255]
NullpointerException occurred converting .odt file to .pdf file.

I would like to check the null pointer.

``` java
Caused by: java.lang.NullPointerException
	at org.odftoolkit.odfdom.converter.pdf.internal.ElementVisitorForIText.createAndAddChunk(ElementVisitorForIText.java:787)
	at org.odftoolkit.odfdom.converter.pdf.internal.ElementVisitorForIText.processTextNode(ElementVisitorForIText.java:772)
	at org.odftoolkit.odfdom.converter.core.ElementVisitorConverter.visit(ElementVisitorConverter.java:85)
	at org.odftoolkit.odfdom.dom.DefaultElementVisitor.visit(DefaultElementVisitor.java:2541)
	at org.odftoolkit.odfdom.dom.element.office.OfficeMasterStylesElement.accept(OfficeMasterStylesElement.java:109)
	at org.odftoolkit.odfdom.converter.pdf.PdfConverter.processBody(PdfConverter.java:122)
	at org.odftoolkit.odfdom.converter.pdf.PdfConverter.doConvert(PdfConverter.java:65)
	... 4 more
```

**Comment by p4535992** [comment]
Same error have you found the cause?
