### ISSUE TITLE
Dynamic image inside foreach syntax in docx document

### ISSUE THREAD

**Issue by Halcens** [opensagres/xdocreport#279]
Hello, 

I have downloaded the samples, for test the dynamic image in List. 
When I tried to moved the logo picture of table to foreach syntax velocity in the docx document, the console displays the following error : 
`Caused by: fr.opensagres.xdocreport.core.XDocReportException: Image provider for field [photo] cannot be null!
	at fr.opensagres.xdocreport.document.images.AbstractImageRegistry.processNullImage(AbstractImageRegistry.java:106)
	at fr.opensagres.xdocreport.document.images.AbstractImageRegistry.registerImage(AbstractImageRegistry.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.doInvoke(UberspectImpl.java:395)
	at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.invoke(UberspectImpl.java:384)
	at org.apache.velocity.runtime.parser.node.ASTMethod.execute(ASTMethod.java:173)
	... 22 more`

Is it possible to use dymamic image inside  foreach syntax ? 

Best regards and tx for this project ! 

[DocxProjectWithVelocityAndImageList.docx](https://github.com/opensagres/xdocreport/files/1733534/DocxProjectWithVelocityAndImageList.docx)

**Comment by angelozerr** [comment]
Plese see sample https://github.com/opensagres/xdocreport.samples/blob/master/samples/fr.opensagres.xdocreport.samples.docxandvelocity/src/fr/opensagres/xdocreport/samples/docxandvelocity/DocxProjectWithVelocityAndImageList.java

**Comment by Halcens** [comment]
Hi, thanx for yu answer, 

I cloned the repository and i use this class, i have juste moved the image in docx inside the foreach.

**Comment by angelozerr** [comment]
If I remember it works only with table (where #foreach is generated automaticly) but it doesn't work if you try to use it inside a written #foreach like you have tried.

**Comment by Halcens** [comment]
Thanx for the explication,  

Do you have an idea, how I can put dynamic image without table ?

**Comment by angelozerr** [comment]
> Do you have an idea, how I can put dynamic image without table ?

To be honnest with you, I don't remember how it works and I have no time today how to manage this feature. Good luck!

**Comment by Halcens** [comment]
Ok, Thanx for yu answer, 
I'm going to try to understand the code, if I have a solution, I will give the solution in the present topic :).

**Comment by vinyoliver** [comment]
@Halcens by any chance have you been able to solve this problem? I'm facing the same problem :(
