### ISSUE TITLE
Inserted dynamic Image gives Parsing error

### ISSUE THREAD

**Issue by Mimi6257** [opensagres/xdocreport#28]
Hi 

I've got a problem when I insert more than 1 template image in a docx.

I tested my code with your docx "DocxProjectWithFreemarkerAndImage.docx" , my code works, with all images .
But if I use a new docx with more than 1 template image, I get this error : 

-

freemarker.core.ParseException: Parsing error in template "fr.opensagres.xdocreport.document.docx.DocxReport@6bba64!word/document.xml" in line 4, column 9352:
Encountered "[/#escape]", but was expecting one of:
    \<ATTEMPT>
    \<IF>
    \<ELSE_IF> 
    .........
	at freemarker.core.FMParser.generateParseException(FMParser.java:4672)
	at freemarker.core.FMParser.jj_consume_token(FMParser.java:4543)
	at freemarker.core.FMParser.If(FMParser.java:1208)
	at freemarker.core.FMParser.FreemarkerDirective(FMParser.java:2347)
	at freemarker.core.FMParser.Content(FMParser.java:2593)
	at freemarker.core.FMParser.OptionalBlock(FMParser.java:2761)
	at freemarker.core.FMParser.Escape(FMParser.java:2279)
	at freemarker.core.FMParser.FreemarkerDirective(FMParser.java:2420)
	at freemarker.core.FMParser.Content(FMParser.java:2593)
	at freemarker.core.FMParser.OptionalBlock(FMParser.java:2761)
	at freemarker.core.FMParser.Root(FMParser.java:2933)
	at freemarker.template.Template.<init>(Template.java:193)
	at freemarker.cache.TemplateCache.loadTemplate(TemplateCache.java:419)
	at freemarker.cache.TemplateCache.getTemplate(TemplateCache.java:330)
	at freemarker.cache.TemplateCache.getTemplate(TemplateCache.java:205)
	at freemarker.template.Configuration.getTemplate(Configuration.java:740)
	at freemarker.template.Configuration.getTemplate(Configuration.java:665)
	at fr.opensagres.xdocreport.template.freemarker.FreemarkerTemplateEngine.processWithCache(FreemarkerTemplateEngine.java:110)
	at fr.opensagres.xdocreport.template.AbstractTemplateEngine.process(AbstractTemplateEngine.java:111)
	at fr.opensagres.xdocreport.template.AbstractTemplateEngine.process(AbstractTemplateEngine.java:83)
	at fr.opensagres.xdocreport.document.AbstractXDocReport.processTemplateEngine(AbstractXDocReport.java:775)
	at fr.opensagres.xdocreport.document.AbstractXDocReport.process(AbstractXDocReport.java:521)
	at fr.opensagres.xdocreport.document.AbstractXDocReport.process(AbstractXDocReport.java:487)
	at fr.opensagres.xdocreport.samples.docxandfreemarker.Test1.execute(Test1.java:169)

-

It works with only one image, but not with more.
It doesn't work also if I insert one more new image to your docx "DocxProjectWithFreemarkerAndImage.docx"

I think I make something wrong when I insert the new image, but I don't find out.
I insert new image as explain in https://code.google.com/p/xdocreport/wiki/DocxReportingJavaMainDynamicImage.

Did you already see this problem ?

Thanks for reading my issue

**Comment by Mimi6257** [comment]
I forgot some details : 

xDocReport : 1.0.4
freemarker : 2.3.20
java : 1.6
word : MS Word 2013

**Comment by angelozerr** [comment]
Please share your docx + java main (in your github) which causes problem. Thanks.

**Comment by Mimi6257** [comment]
I think I found the problem
It depend how I insert image in the docx, which separator bitween images (nothing, space, line return, tab, ...) , which text wrapping I use(In line in text, In front of text, .... ) , where the image is placed (in the document itself, in a table, in a text zone)
Some combinaison doesn't work, I'm testing all possibilities to check which are not supported
