### ISSUE TITLE
fr.opensagres.xdocreport.converter.XDocConverterException: java.lang.IllegalAccessError

### ISSUE THREAD

**Issue by filippucher** [opensagres/xdocreport#34]
Hello,
I've implemented web application, REST service, where I convert either odt or docx documents to pdf. I don't use xdocreport REST sample implementation but mine based on resteasy. Then installed war archive on jboss 7.1 AS.

I encounter exception in both cases (odt and docx). ODT is the same as https://code.google.com/p/xdocreport/issues/detail?id=470
When testing report/convert as console application (no REST service there, just java main), everything runs fine.

xdocreport version: 1.0.5
iText version: 2.1.7

pom.xml:

		<dependency>
			<groupId>fr.opensagres.xdocreport</groupId>
			<artifactId>fr.opensagres.xdocreport.document.odt</artifactId>
			<version>1.0.5</version>
		</dependency>
				
		<dependency>
			<groupId>fr.opensagres.xdocreport</groupId>
			<artifactId>fr.opensagres.xdocreport.document.docx</artifactId>
			<version>1.0.5</version>
		</dependency>
		
		<dependency>
			<groupId>fr.opensagres.xdocreport</groupId>
			<artifactId>fr.opensagres.xdocreport.template.velocity</artifactId>
			<version>1.0.5</version>
		</dependency>
		
		<dependency>
			<groupId>fr.opensagres.xdocreport</groupId>
			<artifactId>fr.opensagres.xdocreport.converter.odt.odfdom</artifactId>
			<version>1.0.5</version>
		</dependency>		
		
		<dependency>
			<groupId>fr.opensagres.xdocreport</groupId>
			<artifactId>fr.opensagres.xdocreport.converter.docx.xwpf</artifactId>
			<version>1.0.5</version>
		</dependency>

Java code fragment:
```java
@GET
@Produces( "application/pdf" )
@Path( "/document" )
public Response convert()
{
  StreamingOutput output = new StreamingOutput()
  {
    public void write( OutputStream out )
    {
      // try omitted here
      InputStream in = ServiceImpl.class.getClassLoader().getResourceAsStream("template.odt"); // or docx
      IXDocReport report = XDocReportRegistry.getRegistry().loadReport(in,TemplateEngineKind.Velocity);
    
      IContext context = report.createContext();
      context.put("salutation", "Bonjour le monde!");
    
      Options options = Options.getTo(ConverterTypeTo.PDF).via(ConverterTypeVia.ODFDOM); // or XWPF
      report.convert(context, options, out);
      // catch block omitted here
    }
  };
  ResponseBuilder responseBuilder = Response.ok( output);
  responseBuilder.header( HttpHeaderUtils.CONTENT_DISPOSITION_HEADER, HttpHeaderUtils.getAttachmentFileName( "document.pdf" ));
            
  return responseBuilder.build();
}
```

ODFDOM version log:
````log
fr.opensagres.xdocreport.converter.XDocConverterException: java.lang.IllegalAccessError: tried to access class com.lowagie.text.pdf.PdfDocument from class fr.opensagres.xdocreport.itext.extension.ExtendedPdfWriter
	at fr.opensagres.xdocreport.document.AbstractXDocReport.convert(AbstractXDocReport.java:748) ~[fr.opensagres.xdocreport.document-1.0.5.jar:1.0.5]
	at my.webapp.impl.ServiceImpl$1.write(ServiceImpl.java:102) ~[classes:na]
	at org.jboss.resteasy.plugins.providers.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:32) [resteasy-jaxrs-2.3.2.Final.jar!/:na]
	at org.jboss.resteasy.plugins.providers.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:17) [resteasy-jaxrs-2.3.2.Final.jar!/:na]
	at org.jboss.resteasy.core.interception.MessageBodyWriterContextImpl.proceed(MessageBodyWriterContextImpl.java:117) [resteasy-jaxrs-2.3.2.Final.jar!/:na]
	at org.jboss.resteasy.plugins.interceptors.encoding.GZIPEncodingInterceptor.write(GZIPEncodingInterceptor.java:100) [resteasy-jaxrs-2.3.2.Final.jar!/:na]
	at org.jboss.resteasy.core.interception.MessageBodyWriterContextImpl.proceed(MessageBodyWriterContextImpl.java:123) [resteasy-jaxrs-2.3.2.Final.jar!/:na]
	at org.jboss.resteasy.core.ServerResponse.writeTo(ServerResponse.java:250) [resteasy-jaxrs-2.3.2.Final.jar!/:na]
	at org.jboss.resteasy.core.SynchronousDispatcher.writeJaxrsResponse(SynchronousDispatcher.java:585) [resteasy-jaxrs-2.3.2.Final.jar!/:na]
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:506) [resteasy-jaxrs-2.3.2.Final.jar!/:na]
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:119) [resteasy-jaxrs-2.3.2.Final.jar!/:na]
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:208) [resteasy-jaxrs-2.3.2.Final.jar!/:na]
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:55) [resteasy-jaxrs-2.3.2.Final.jar!/:na]
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:50) [resteasy-jaxrs-2.3.2.Final.jar!/:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:847) [jboss-servlet-api_3.0_spec-1.0.0.Final.jar!/:1.0.0.Final]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:329) [jbossweb-7.0.13.Final.jar!/:na]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:248) [jbossweb-7.0.13.Final.jar!/:na]
	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116) [portal-service.jar!/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.6.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39) ~[na:1.6.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) ~[na:1.6.0_45]
	at java.lang.reflect.Method.invoke(Method.java:597) ~[na:1.6.0_45]
	at com.liferay.portal.kernel.bean.ClassLoaderBeanHandler.invoke(ClassLoaderBeanHandler.java:67) [portal-service.jar!/:na]
	at com.sun.proxy.$Proxy2286.doFilter(Unknown Source) [na:na]
	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116) [portal-service.jar!/:na]
	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDirectCallFilter(InvokerFilterChain.java:165) [portal-service.jar!/:na]
	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:96) [portal-service.jar!/:na]
	at com.liferay.portal.kernel.servlet.PortalClassLoaderFilter.doFilter(PortalClassLoaderFilter.java:74) [portal-service.jar!/:na]
	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:204) [portal-service.jar!/:na]
	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:109) [portal-service.jar!/:na]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88) [spring-web-4.1.4.RELEASE.jar:4.1.4.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.1.4.RELEASE.jar:4.1.4.RELEASE]
	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:204) [portal-service.jar!/:na]
	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:109) [portal-service.jar!/:na]
	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilter.doFilter(InvokerFilter.java:96) [portal-service.jar!/:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:280) [jbossweb-7.0.13.Final.jar!/:na]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:248) [jbossweb-7.0.13.Final.jar!/:na]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:275) [jbossweb-7.0.13.Final.jar!/:na]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:161) [jbossweb-7.0.13.Final.jar!/:na]
	at org.jboss.as.jpa.interceptor.WebNonTxEmCloserValve.invoke(WebNonTxEmCloserValve.java:50) [jboss-as-jpa-7.1.1.Final.jar!/:7.1.1.Final]
	at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:153) [jboss-as-web-7.1.1.Final.jar!/:7.1.1.Final]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:155) [jbossweb-7.0.13.Final.jar!/:na]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102) [jbossweb-7.0.13.Final.jar!/:na]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109) [jbossweb-7.0.13.Final.jar!/:na]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:368) [jbossweb-7.0.13.Final.jar!/:na]
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:877) [jbossweb-7.0.13.Final.jar!/:na]
	at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:671) [jbossweb-7.0.13.Final.jar!/:na]
	at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:930) [jbossweb-7.0.13.Final.jar!/:na]
	at java.lang.Thread.run(Thread.java:662) [na:1.6.0_45]
Caused by: java.lang.IllegalAccessError: tried to access class com.lowagie.text.pdf.PdfDocument from class fr.opensagres.xdocreport.itext.extension.ExtendedPdfWriter
	at fr.opensagres.xdocreport.itext.extension.ExtendedPdfWriter.getInstance(ExtendedPdfWriter.java:48) ~[fr.opensagres.xdocreport.itext.extension-1.0.5.jar:1.0.5]
	at fr.opensagres.xdocreport.itext.extension.ExtendedDocument.<init>(ExtendedDocument.java:62) ~[fr.opensagres.xdocreport.itext.extension-1.0.5.jar:1.0.5]
	at org.odftoolkit.odfdom.converter.pdf.internal.stylable.StylableDocument.<init>(StylableDocument.java:76) ~[org.odftoolkit.odfdom.converter.pdf-1.0.5.jar:1.0.5]
	at org.odftoolkit.odfdom.converter.pdf.internal.ElementVisitorForIText.<init>(ElementVisitorForIText.java:148) ~[org.odftoolkit.odfdom.converter.pdf-1.0.5.jar:1.0.5]
	at org.odftoolkit.odfdom.converter.pdf.PdfConverter.processBody(PdfConverter.java:114) ~[org.odftoolkit.odfdom.converter.pdf-1.0.5.jar:1.0.5]
	at org.odftoolkit.odfdom.converter.pdf.PdfConverter.doConvert(PdfConverter.java:65) ~[org.odftoolkit.odfdom.converter.pdf-1.0.5.jar:1.0.5]
	at org.odftoolkit.odfdom.converter.pdf.PdfConverter.doConvert(PdfConverter.java:43) ~[org.odftoolkit.odfdom.converter.pdf-1.0.5.jar:1.0.5]
	at org.odftoolkit.odfdom.converter.core.AbstractODFConverter.convert(AbstractODFConverter.java:42) ~[org.odftoolkit.odfdom.converter.core-1.0.5.jar:1.0.5]
	at fr.opensagres.xdocreport.converter.odt.odfdom.itext.ODF2PDFViaITextConverter.convert(ODF2PDFViaITextConverter.java:62) ~[fr.opensagres.xdocreport.converter.odt.odfdom-1.0.5.jar:1.0.5]
	at fr.opensagres.xdocreport.document.AbstractXDocReport.convert(AbstractXDocReport.java:713) ~[fr.opensagres.xdocreport.document-1.0.5.jar:1.0.5]
	... 48 common frames omitted
````

XWPF version log:
````log
fr.opensagres.xdocreport.converter.XDocConverterException: java.lang.IllegalAccessError: com/lowagie/text/pdf/PdfDocument
	at fr.opensagres.xdocreport.document.AbstractXDocReport.convert(AbstractXDocReport.java:748) ~[fr.opensagres.xdocreport.document-1.0.5.jar:1.0.5]
	at my.webapp.impl.ServiceImpl$1.write(ServiceImpl.java:102) ~[classes:na]
	at org.jboss.resteasy.plugins.providers.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:32) [resteasy-jaxrs-2.3.2.Final.jar!/:na]
	at org.jboss.resteasy.plugins.providers.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:17) [resteasy-jaxrs-2.3.2.Final.jar!/:na]
	at org.jboss.resteasy.core.interception.MessageBodyWriterContextImpl.proceed(MessageBodyWriterContextImpl.java:117) [resteasy-jaxrs-2.3.2.Final.jar!/:na]
	at org.jboss.resteasy.plugins.interceptors.encoding.GZIPEncodingInterceptor.write(GZIPEncodingInterceptor.java:100) [resteasy-jaxrs-2.3.2.Final.jar!/:na]
	at org.jboss.resteasy.core.interception.MessageBodyWriterContextImpl.proceed(MessageBodyWriterContextImpl.java:123) [resteasy-jaxrs-2.3.2.Final.jar!/:na]
	at org.jboss.resteasy.core.ServerResponse.writeTo(ServerResponse.java:250) [resteasy-jaxrs-2.3.2.Final.jar!/:na]
	at org.jboss.resteasy.core.SynchronousDispatcher.writeJaxrsResponse(SynchronousDispatcher.java:585) [resteasy-jaxrs-2.3.2.Final.jar!/:na]
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:506) [resteasy-jaxrs-2.3.2.Final.jar!/:na]
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:119) [resteasy-jaxrs-2.3.2.Final.jar!/:na]
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:208) [resteasy-jaxrs-2.3.2.Final.jar!/:na]
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:55) [resteasy-jaxrs-2.3.2.Final.jar!/:na]
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:50) [resteasy-jaxrs-2.3.2.Final.jar!/:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:847) [jboss-servlet-api_3.0_spec-1.0.0.Final.jar!/:1.0.0.Final]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:329) [jbossweb-7.0.13.Final.jar!/:na]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:248) [jbossweb-7.0.13.Final.jar!/:na]
	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116) [portal-service.jar!/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.6.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39) ~[na:1.6.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) ~[na:1.6.0_45]
	at java.lang.reflect.Method.invoke(Method.java:597) ~[na:1.6.0_45]
	at com.liferay.portal.kernel.bean.ClassLoaderBeanHandler.invoke(ClassLoaderBeanHandler.java:67) [portal-service.jar!/:na]
	at com.sun.proxy.$Proxy2286.doFilter(Unknown Source) [na:na]
	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116) [portal-service.jar!/:na]
	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDirectCallFilter(InvokerFilterChain.java:165) [portal-service.jar!/:na]
	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:96) [portal-service.jar!/:na]
	at com.liferay.portal.kernel.servlet.PortalClassLoaderFilter.doFilter(PortalClassLoaderFilter.java:74) [portal-service.jar!/:na]
	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:204) [portal-service.jar!/:na]
	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:109) [portal-service.jar!/:na]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88) [spring-web-4.1.4.RELEASE.jar:4.1.4.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.1.4.RELEASE.jar:4.1.4.RELEASE]
	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:204) [portal-service.jar!/:na]
	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:109) [portal-service.jar!/:na]
	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilter.doFilter(InvokerFilter.java:96) [portal-service.jar!/:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:280) [jbossweb-7.0.13.Final.jar!/:na]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:248) [jbossweb-7.0.13.Final.jar!/:na]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:275) [jbossweb-7.0.13.Final.jar!/:na]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:161) [jbossweb-7.0.13.Final.jar!/:na]
	at org.jboss.as.jpa.interceptor.WebNonTxEmCloserValve.invoke(WebNonTxEmCloserValve.java:50) [jboss-as-jpa-7.1.1.Final.jar!/:7.1.1.Final]
	at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:153) [jboss-as-web-7.1.1.Final.jar!/:7.1.1.Final]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:155) [jbossweb-7.0.13.Final.jar!/:na]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102) [jbossweb-7.0.13.Final.jar!/:na]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109) [jbossweb-7.0.13.Final.jar!/:na]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:368) [jbossweb-7.0.13.Final.jar!/:na]
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:877) [jbossweb-7.0.13.Final.jar!/:na]
	at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:671) [jbossweb-7.0.13.Final.jar!/:na]
	at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:930) [jbossweb-7.0.13.Final.jar!/:na]
	at java.lang.Thread.run(Thread.java:662) [na:1.6.0_45]
Caused by: java.lang.IllegalAccessError: com/lowagie/text/pdf/PdfDocument
	at fr.opensagres.xdocreport.itext.extension.ExtendedPdfWriter.getInstance(ExtendedPdfWriter.java:48) ~[fr.opensagres.xdocreport.itext.extension-1.0.5.jar:1.0.5]
	at fr.opensagres.xdocreport.itext.extension.ExtendedDocument.<init>(ExtendedDocument.java:62) ~[fr.opensagres.xdocreport.itext.extension-1.0.5.jar:1.0.5]
	at org.apache.poi.xwpf.converter.pdf.internal.elements.StylableDocument.<init>(StylableDocument.java:78) ~[org.apache.poi.xwpf.converter.pdf-1.0.5.jar:1.0.5]
	at org.apache.poi.xwpf.converter.pdf.internal.PdfMapper.startVisitDocument(PdfMapper.java:159) ~[org.apache.poi.xwpf.converter.pdf-1.0.5.jar:1.0.5]
	at org.apache.poi.xwpf.converter.pdf.internal.PdfMapper.startVisitDocument(PdfMapper.java:111) ~[org.apache.poi.xwpf.converter.pdf-1.0.5.jar:1.0.5]
	at org.apache.poi.xwpf.converter.core.XWPFDocumentVisitor.start(XWPFDocumentVisitor.java:196) ~[org.apache.poi.xwpf.converter.core-1.0.5.jar:1.0.5]
	at org.apache.poi.xwpf.converter.pdf.PdfConverter.doConvert(PdfConverter.java:56) ~[org.apache.poi.xwpf.converter.pdf-1.0.5.jar:1.0.5]
	at org.apache.poi.xwpf.converter.pdf.PdfConverter.doConvert(PdfConverter.java:38) ~[org.apache.poi.xwpf.converter.pdf-1.0.5.jar:1.0.5]
	at org.apache.poi.xwpf.converter.core.AbstractXWPFConverter.convert(AbstractXWPFConverter.java:45) ~[org.apache.poi.xwpf.converter.core-1.0.5.jar:1.0.5]
	at fr.opensagres.xdocreport.converter.docx.poi.itext.XWPF2PDFViaITextConverter.convert(XWPF2PDFViaITextConverter.java:67) ~[fr.opensagres.xdocreport.converter.docx.xwpf-1.0.5.jar:1.0.5]
	at fr.opensagres.xdocreport.document.AbstractXDocReport.convert(AbstractXDocReport.java:713) ~[fr.opensagres.xdocreport.document-1.0.5.jar:1.0.5]
	... 48 common frames omitted
````

**Comment by angelozerr** [comment]
Check you have only iText 2.1.7 in your classpath.

**Comment by filippucher** [comment]
Hi Angelo, good point!

Found itext-1.3.jar along with itext-2.1.7.jar in WEB-INF/lib folder of the project war. It came as transitive from some other dependency.

When corrected and redeployed, it runs just fine.

Merci beaucoup.
