### ISSUE TITLE
NullPointerException in RBufferedRegion.java

### ISSUE THREAD

**Issue by harifucks** [opensagres/xdocreport#36]
HI:
I try to use XDocReport to merge data into the Word file (docx files), then exception happening

Exception in thread "main" java.lang.NullPointerException
at fr.opensagres.xdocreport.document.docx.preprocessor.sax.RBufferedRegion.setTContent(RBufferedRegion.java:65)
at fr.opensagres.xdocreport.document.docx.preprocessor.sax.PBufferedRegion.process(PBufferedRegion.java:216)
at fr.opensagres.xdocreport.document.docx.preprocessor.sax.DocxBufferedDocument.onEndEndElement(DocxBufferedDocument.java:320)
at fr.opensagres.xdocreport.document.preprocessor.sax.BufferedDocumentContentHandler.endElement(BufferedDocumentContentHandler.java:273)
at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(Unknown Source)
at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(Unknown Source)
at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source)
at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(Unknown Source)
at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
at fr.opensagres.xdocreport.document.preprocessor.sax.SAXXDocPreprocessor.preprocess(SAXXDocPreprocessor.java:62)
at fr.opensagres.xdocreport.document.preprocessor.sax.SAXXDocPreprocessor.preprocess(SAXXDocPreprocessor.java:47)
at fr.opensagres.xdocreport.document.preprocessor.AbstractXDocPreprocessor.preprocess(AbstractXDocPreprocessor.java:88)
at fr.opensagres.xdocreport.document.AbstractXDocReport.doPreprocessorIfNeeded(AbstractXDocReport.java:366)
at fr.opensagres.xdocreport.document.AbstractXDocReport.convert(AbstractXDocReport.java:694)
at word.DocxProjectWithVelocity2PDF.main(DocxProjectWithVelocity2PDF.java:208)

I cannot upload my DOCX and java file. I find the same issue in https://code.google.com/p/xdocreport/issues/detail?id=424. But I have no idea that what is 1.0.5-SNAPSHOT?

What version of the product are you using? On what operating system?
XDocReport 1.0.4, Windows 7 64Bit. Spring/Eclipse 3.2 with JDK6

**Comment by angelozerr** [comment]
@harifucks please share your docx by creating a github project. Without your docx, we cannot do something. Thanks!

**Comment by harifucks** [comment]
HI
I upload the document, and there are Traditional Chinese words in the document but all merge fields are English. Thanks a lot.

**Comment by harifucks** [comment]
HI
I already create a github project and share a docx file named "HiLink FTTB.docx" in the /src/word.
Thanks a lot.

**Comment by angelozerr** [comment]
I have fixed the problem. But your docx is very strange. problem came from with applyitem MERGEFIELD :

```xml
<w:p w:rsidR="003541BC" w:rsidRPr="00ED4991" w:rsidRDefault="003541BC"
	w:rsidP="001A7791">
	<w:pPr>
		<w:jc w:val="center" />
		<w:rPr>
			<w:rFonts w:ascii="Arial" w:eastAsia="標楷體" w:hAnsi="Arial" />
			<w:sz w:val="20" />
		</w:rPr>
	</w:pPr>
	<w:r w:rsidRPr="00ED4991">
		<w:rPr>
			<w:rFonts w:ascii="Arial" w:eastAsia="標楷體" w:hAnsi="Arial" />
		</w:rPr>
		<w:fldChar w:fldCharType="begin" />
	</w:r>
	<w:r w:rsidRPr="00ED4991">
		<w:rPr>
			<w:rFonts w:ascii="Arial" w:eastAsia="標楷體" w:hAnsi="Arial" />
		</w:rPr>
		<w:instrText xml:space="preserve"> IF </w:instrText>
	</w:r>
	<w:r w:rsidRPr="00ED4991">
		<w:rPr>
			<w:rFonts w:ascii="Arial" w:eastAsia="標楷體" w:hAnsi="Arial" />
		</w:rPr>
		<w:fldChar w:fldCharType="begin" />
	</w:r>
	<w:r w:rsidRPr="00ED4991">
		<w:rPr>
			<w:rFonts w:ascii="Arial" w:eastAsia="標楷體" w:hAnsi="Arial" />
		</w:rPr>
		<w:instrText xml:space="preserve"> MERGEFIELD applyitem </w:instrText>
	</w:r>
	<w:r w:rsidRPr="00ED4991">
		<w:rPr>
			<w:rFonts w:ascii="Arial" w:eastAsia="標楷體" w:hAnsi="Arial" />
		</w:rPr>
		<w:fldChar w:fldCharType="separate" />
	</w:r>
	<w:r>
		<w:rPr>
			<w:rFonts w:ascii="Arial" w:eastAsia="標楷體" w:hAnsi="Arial" />
			<w:noProof />
		</w:rPr>
		<w:instrText>«applyitem»</w:instrText>
	</w:r>
	<w:r w:rsidRPr="00ED4991">
		<w:rPr>
			<w:rFonts w:ascii="Arial" w:eastAsia="標楷體" w:hAnsi="Arial" />
		</w:rPr>
		<w:fldChar w:fldCharType="end" />
	</w:r>
	<w:r w:rsidRPr="00ED4991">
		<w:rPr>
			<w:rFonts w:ascii="Arial" w:eastAsia="標楷體" w:hAnsi="Arial" />
		</w:rPr>
		<w:instrText xml:space="preserve"> = </w:instrText>
	</w:r>
	<w:r w:rsidRPr="00ED4991">
		<w:rPr>
			<w:rFonts w:ascii="Arial" w:eastAsia="標楷體" w:hAnsi="Arial"
				w:hint="eastAsia" />
		</w:rPr>
		<w:instrText>1</w:instrText>
	</w:r>
	<w:r w:rsidRPr="00ED4991">
		<w:rPr>
			<w:rFonts w:ascii="Arial" w:eastAsia="標楷體" w:hAnsi="Arial" />
		</w:rPr>
		<w:instrText xml:space="preserve"> "</w:instrText>
	</w:r>
	<w:r w:rsidRPr="00ED4991">
		<w:rPr>
			<w:rFonts w:ascii="Arial" w:eastAsia="標楷體" w:hAnsi="Arial" />
		</w:rPr>
		<w:sym w:font="Wingdings" w:char="00FC" />
	</w:r>
	<w:r w:rsidRPr="00ED4991">
		<w:rPr>
			<w:rFonts w:ascii="Arial" w:eastAsia="標楷體" w:hAnsi="Arial" />
		</w:rPr>
		<w:instrText>" "</w:instrText>
	</w:r>
	<w:r w:rsidRPr="00ED4991">
		<w:rPr>
			<w:rFonts w:ascii="Arial" w:eastAsia="標楷體" w:hAnsi="Arial" />
			<w:b />
		</w:rPr>
		<w:instrText>"</w:instrText>
	</w:r>
	<w:r w:rsidRPr="00ED4991">
		<w:rPr>
			<w:rFonts w:ascii="Arial" w:eastAsia="標楷體" w:hAnsi="Arial" />
		</w:rPr>
		<w:instrText xml:space="preserve"> </w:instrText>
	</w:r>
	<w:r w:rsidRPr="00ED4991">
		<w:rPr>
			<w:rFonts w:ascii="Arial" w:eastAsia="標楷體" w:hAnsi="Arial" />
		</w:rPr>
		<w:fldChar w:fldCharType="end" />
	</w:r>
</w:p>
```

which don't define a w:t element. It seems that this XML describtion is a dead code, because it doesn't appear when docx is opened with MS Word.

My fix is very basic. I don't preprocess teh mergefield when w:t doesn't exist.

@harifucks pay attention, your mergefield name is not correct you must add a $ before your name, otherwise Velocity will not able to replace it.

**Comment by harifucks** [comment]
HI
Thanks, I am researching your answers.

**Comment by harifucks** [comment]
Excuse me sir
I use Eclipse instead of Maven, and it is a big deal for a novice to rebuild the project. Would you please me a URL or a beta zip/jar file which is corrected and can be used directly. Thanks a lot.
