### ISSUE TITLE
ODF table row loop issues - element type "text:p" must be terminated by the matching end-tag 

### ISSUE THREAD

**Issue by Beowulf786** [opensagres/xdocreport#389]
Hi there,

We've been using ODF -> PDF conversion for generating one of our timesheet reports.

When developing this report, several times I've managed to get myself in a state where the report works correctly however if I open the ODF document in Open Office or Libre Office and hit save (with no changes), it re-formats the source XML significantly and then the following error occurs:

[error] o.o.o.p.OdfPackageDocument - null org.xml.sax.SAXParseException: The element type "text:p" must be terminated by the matching end-tag "</text:p>". at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:na] at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:na] at org.odftoolkit.odfdom.pkg.OdfFileDom.initialize(OdfFileDom.java:142) [odfdom-java-0.8.7.jar:na] at org.odftoolkit.odfdom.dom.OdfContentDom.initialize(OdfContentDom.java:55) [odfdom-java-0.8.7.jar:na] at org.odftoolkit.odfdom.pkg.OdfFileDom.<init>(OdfFileDom.java:87) [odfdom-java-0.8.7.jar:na] at org.odftoolkit.odfdom.dom.OdfContentDom.<init>(OdfContentDom.java:45) [odfdom-java-0.8.7.jar:na] at org.odftoolkit.odfdom.pkg.OdfFileDom.newFileDom(OdfFileDom.java:110) [odfdom-java-0.8.7.jar:na] at org.odftoolkit.odfdom.pkg.OdfPackageDocument.getFileDom(OdfPackageDocument.java:281) [odfdom-java-0.8.7.jar:na] at org.odftoolkit.odfdom.dom.OdfSchemaDocument.getFileDom(OdfSchemaDocument.java:312) [odfdom-java-0.8.7.jar:na]

**Comment by Beowulf786** [comment]
Can some one tell me how to resolve the this error?
