### ISSUE TITLE
DOCX--> PDF Hyperlink or Image in Header or Footer throws Error

### ISSUE THREAD

**Issue by sammad** [opensagres/xdocreport#390]
Hello, 
The below exception is thrown if a word document's header or footer have a hyperlink or image. I would be happy to contribute to resolve this issue. Attached with this email is a document 
[TestHeaderWithHyperlink.docx](https://github.com/opensagres/xdocreport/files/3824342/TestHeaderWithHyperlink.docx)

```
fr.opensagres.poi.xwpf.converter.core.XWPFConverterException: java.lang.RuntimeException: Not all annotations could be added to the document (the document doesn't have enough pages).
	at fr.opensagres.poi.xwpf.converter.pdf.PdfConverter.doConvert(PdfConverter.java:71)
	at fr.opensagres.poi.xwpf.converter.pdf.PdfConverter.doConvert(PdfConverter.java:1)
	.....
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)
```
Caused by: java.lang.RuntimeException: Not all annotations could be added to the document (the document doesn't have enough pages).

**Comment by angelozerr** [comment]
Fixed with https://github.com/opensagres/xdocreport/pull/392
