### ISSUE TITLE
NullpointerException while converting .ods to .pdf

### ISSUE THREAD

**Issue by kassssy** [opensagres/xdocreport#393]
Hello there,

when I try to convert an ods-File to a pdf-File I get the following exception : 

_at fr.opensagres.odfdom.converter.pdf.internal.ElementVisitorForIText.addITextContainer(ElementVisitorForIText.java:843)
	at fr.opensagres.odfdom.converter.pdf.internal.ElementVisitorForIText.addITextContainer(ElementVisitorForIText.java:831)
	at fr.opensagres.odfdom.converter.pdf.internal.ElementVisitorForIText.visit(ElementVisitorForIText.java:510)
	at org.odftoolkit.odfdom.dom.element.table.TableTableElement.accept(TableTableElement.java:678)
	at fr.opensagres.odfdom.converter.core.ElementVisitorConverter.visit(ElementVisitorConverter.java:83)
	at org.odftoolkit.odfdom.dom.DefaultElementVisitor.visit(DefaultElementVisitor.java:2589)
	at org.odftoolkit.odfdom.dom.element.office.OfficeSpreadsheetElement.accept(OfficeSpreadsheetElement.java:331)
	at fr.opensagres.odfdom.converter.pdf.PdfConverter.processBody(PdfConverter.java:138)
	at fr.opensagres.odfdom.converter.pdf.PdfConverter.doConvert(PdfConverter.java:66)_

This is the code I'm using to convert : 

public static void convertODStoPDF( String documentPath, String outputPath ) throws Exception {

		// 1) Load ODT into ODFDOM OdfTextDocument 
		InputStream in= new FileInputStream(new File(documentPath));
		OdfSpreadsheetDocument document = OdfSpreadsheetDocument.loadDocument(in);

		// 2) Prepare Pdf options
		PdfOptions options = PdfOptions.create();

		// 3) Convert OdfTextDocument to PDF via IText
		OutputStream out = new FileOutputStream(new File(outputPath));
				
		PdfConverter.getInstance().convert(document, out, options);
	}

The .ods-File contains only one sheet where 2 columns are filled with text. 

Does anyone knows the problem or has a solution ?
Thanks :)

**Comment by angelozerr** [comment]
The ODS -> PDF converter is an experimental support, so it needs to improve it.
