### ISSUE TITLE
fr.opensagres.poi.xwpf.converter.core.XWPFConverterException: org.apache.xmlbeans.impl.values.XmlValueOutOfRangeException: Invalid integer value: When converting docx to pdf

### ISSUE THREAD

**Issue by jeffreydelacruz** [opensagres/xdocreport#397]
fr.opensagres.poi.xwpf.converter.core.XWPFConverterException: org.apache.xmlbeans.impl.values.XmlValueOutOfRangeException: Invalid integer value: 524.9999999999999
	at fr.opensagres.poi.xwpf.converter.pdf.PdfConverter.doConvert(PdfConverter.java:71)
	at fr.opensagres.poi.xwpf.converter.pdf.PdfConverter.doConvert(PdfConverter.java:39)
	at fr.opensagres.poi.xwpf.converter.core.AbstractXWPFConverter.convert(AbstractXWPFConverter.java:46)
	at com.piq.strata.util.Test.main(Test.java:35)
Caused by: org.apache.xmlbeans.impl.values.XmlValueOutOfRangeException: Invalid integer value: 524.9999999999999
	at org.apache.xmlbeans.impl.values.XmlObjectBase$ValueOutOfRangeValidationContext.invalid(XmlObjectBase.java:328)
	at org.apache.xmlbeans.impl.values.JavaIntegerHolder.lex(JavaIntegerHolder.java:50)
	at org.apache.xmlbeans.impl.values.JavaIntegerHolderEx.set_text(JavaIntegerHolderEx.java:40)
	at org.apache.xmlbeans.impl.values.XmlObjectBase.update_from_wscanon_text(XmlObjectBase.java:1180)
	at org.apache.xmlbeans.impl.values.XmlObjectBase.check_dated(XmlObjectBase.java:1319)
	at org.apache.xmlbeans.impl.values.JavaIntegerHolder.getBigIntegerValue(JavaIntegerHolder.java:58)
	at org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTIndImpl.getFirstLine(Unknown Source)
	at fr.opensagres.poi.xwpf.converter.core.styles.paragraph.ParagraphIndentationFirstLineValueProvider.getValue(ParagraphIndentationFirstLineValueProvider.java:42)
	at fr.opensagres.poi.xwpf.converter.core.styles.paragraph.ParagraphIndentationFirstLineValueProvider.getValue(ParagraphIndentationFirstLineValueProvider.java:33)
	at fr.opensagres.poi.xwpf.converter.core.styles.paragraph.AbstractIndentationParagraphValueProvider.getValue(AbstractIndentationParagraphValueProvider.java:46)
	at fr.opensagres.poi.xwpf.converter.core.styles.paragraph.AbstractParagraphValueProvider.getValueFromElement(AbstractParagraphValueProvider.java:74)
	at fr.opensagres.poi.xwpf.converter.core.styles.paragraph.AbstractParagraphValueProvider.getValueFromElement(AbstractParagraphValueProvider.java:42)
	at fr.opensagres.poi.xwpf.converter.core.styles.AbstractValueProvider.internalGetValue(AbstractValueProvider.java:51)
	at fr.opensagres.poi.xwpf.converter.core.styles.AbstractValueProvider.getValue(AbstractValueProvider.java:42)
	at fr.opensagres.poi.xwpf.converter.core.styles.XWPFStylesDocument.getIndentationFirstLine(XWPFStylesDocument.java:409)
	at fr.opensagres.poi.xwpf.converter.pdf.internal.PdfMapper.startVisitParagraph(PdfMapper.java:250)
	at fr.opensagres.poi.xwpf.converter.pdf.internal.PdfMapper.startVisitParagraph(PdfMapper.java:100)
	at fr.opensagres.poi.xwpf.converter.core.XWPFDocumentVisitor.visitParagraph(XWPFDocumentVisitor.java:409)
	at fr.opensagres.poi.xwpf.converter.core.XWPFDocumentVisitor.visitBodyElements(XWPFDocumentVisitor.java:263)
	at fr.opensagres.poi.xwpf.converter.core.XWPFDocumentVisitor.visitTableCellBody(XWPFDocumentVisitor.java:1212)
	at fr.opensagres.poi.xwpf.converter.core.XWPFDocumentVisitor.visitCell(XWPFDocumentVisitor.java:1147)
	at fr.opensagres.poi.xwpf.converter.core.XWPFDocumentVisitor.visitTableRow(XWPFDocumentVisitor.java:1049)
	at fr.opensagres.poi.xwpf.converter.core.XWPFDocumentVisitor.visitTableBody(XWPFDocumentVisitor.java:990)
	at fr.opensagres.poi.xwpf.converter.core.XWPFDocumentVisitor.visitTable(XWPFDocumentVisitor.java:972)
	at fr.opensagres.poi.xwpf.converter.core.XWPFDocumentVisitor.visitBodyElements(XWPFDocumentVisitor.java:267)
	at fr.opensagres.poi.xwpf.converter.core.XWPFDocumentVisitor.start(XWPFDocumentVisitor.java:215)
	at fr.opensagres.poi.xwpf.converter.pdf.PdfConverter.doConvert(PdfConverter.java:57)

**Comment by angelozerr** [comment]
Any contribution are welcome!

**Comment by jeffreydelacruz** [comment]
> Any contribution are welcome!

Thanks Angelo, any solution for this error?

**Comment by angelozerr** [comment]
First I suggest you attach the docx which causes problem and hope there will have some people who could fix it.

**Comment by yogeshmallik** [comment]
@jeffreydelacruz Have you got any solution to this problem
