### ISSUE TITLE
Support interactive forms in conversion to PDF

### ISSUE THREAD

**Issue by hibi** [opensagres/xdocreport#4]
Hello guys,

It would be really great to implement support for interactive forms in conversion to PDF. I've successfully tested that it's possible to do it in iText 2.1.7 (even when they claim it's not). Interactive forms can be easily defined in LibreOffice and therefore their support in xDocReport would make it an ultimate tool i believe.

I've posted the question in stackoverflow, see: http://stackoverflow.com/questions/25803252/add-support-to-xdocreport-converts-odt-to-pdf-with-interactive-forms

Thanks in advance for your feedback.

**Comment by shailender-rawat** [comment]
Hi @angelozerr,

Refer to your comments above.

"XDocReport preprocess some XML entries (word/document.xml, content.xml for odt) to update it to set Freemarker/Velocity directive in the right place (ex : generate automaticly #foreach before the first table row when field is marked as list with fields metadata)."

Does that mean, can the Freemarker/ Velocity directive handle the directive for the AcroForm fields as well? Sample AcroForm mentioned below. 

`"><form:text form:name="firstName" form:control-implementation="ooo:com.sun.star.form.component.TextField" xml:id="control1" form:id="control1" form:data-field="$firstName" form:convert-empty-to-null="true"><form:properties>`

**Comment by angelozerr** [comment]
> Does that mean, can the Freemarker/ Velocity directive handle the directive for the AcroForm fields as well? Sample AcroForm mentioned below.

if form-text is in the content.xml for odt, yes it will replace $firstName

**Comment by mwildam** [comment]
I tried this with the 2.0.4 version and a odt template. - I did not find in LibreOffice a form control property, that maps to form:data-field in the odt. I tried adding that manually, but without success. If I write form:data-field="$firstName" I get an error like this (and the same when I set the field form:name="$firstName":

```
org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 10084; The value of attribute "form:name" associated with an element type "form:text" must not contain the '<' character.
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.odftoolkit.odfdom.pkg.OdfFileDom.initialize(OdfFileDom.java:142)
	at org.odftoolkit.odfdom.dom.OdfContentDom.initialize(OdfContentDom.java:55)
	at org.odftoolkit.odfdom.pkg.OdfFileDom.<init>(OdfFileDom.java:87)
	at org.odftoolkit.odfdom.dom.OdfContentDom.<init>(OdfContentDom.java:45)
	at org.odftoolkit.odfdom.pkg.OdfFileDom.newFileDom(OdfFileDom.java:110)
	at org.odftoolkit.odfdom.pkg.OdfPackageDocument.getFileDom(OdfPackageDocument.java:281)
	at org.odftoolkit.odfdom.dom.OdfSchemaDocument.getFileDom(OdfSchemaDocument.java:312)
	at org.odftoolkit.odfdom.dom.OdfSchemaDocument.getContentDom(OdfSchemaDocument.java:190)
	at fr.opensagres.odfdom.converter.pdf.PdfConverter.processStyles(PdfConverter.java:104)
	at fr.opensagres.odfdom.converter.pdf.PdfConverter.doConvert(PdfConverter.java:62)
	at fr.opensagres.odfdom.converter.pdf.PdfConverter.doConvert(PdfConverter.java:44)
	at fr.opensagres.odfdom.converter.core.AbstractODFConverter.convert(AbstractODFConverter.java:42)
	at fr.opensagres.xdocreport.converter.odt.odfdom.itext.ODF2PDFViaITextConverter.convert(ODF2PDFViaITextConverter.java:62)
	at fr.opensagres.xdocreport.document.AbstractXDocReport.convert(AbstractXDocReport.java:710)
```
And if I remove the $ then no exception but interactive PDF form field is not available in the resulting PDF.

I am using this to convert the ODT to PDF:
```
        Options options = Options.getFrom(DocumentKind.ODT).to(ConverterTypeTo.PDF);
        OutputStream output = new FileOutputStream(new File(pdfOutputFileName));
        report.convert(context, options, output);
        System.out.println("File written: " + pdfOutputFileName);
```

**Comment by mwildam** [comment]
Unfortunately I cannot find an example which either just preserves existing interactive form fields from the template into the destination PDF.
