### ISSUE TITLE
NullPointerException while convert DOCX to PDF

### ISSUE THREAD

**Issue by bhaveshkharwa** [opensagres/xdocreport#489]
Getting NullPointerException while convert DOCX to PDF. Find below stacktrace.
`fr.opensagres.poi.xwpf.converter.core.XWPFConverterException: java.lang.NullPointerException
	at fr.opensagres.poi.xwpf.converter.pdf.PdfConverter.doConvert(PdfConverter.java:71)
	at fr.opensagres.poi.xwpf.converter.pdf.PdfConverter.doConvert(PdfConverter.java:39)
	at fr.opensagres.poi.xwpf.converter.core.AbstractXWPFConverter.convert(AbstractXWPFConverter.java:46)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: java.lang.NullPointerException
	at fr.opensagres.poi.xwpf.converter.core.styles.AbstractValueProvider.getValueFromTableStyleIdRow(AbstractValueProvider.java:154)
	at fr.opensagres.poi.xwpf.converter.core.styles.AbstractValueProvider.getValueFromTableStyleId(AbstractValueProvider.java:127)
	at fr.opensagres.poi.xwpf.converter.core.styles.AbstractValueProvider.getValueFromStyles(AbstractValueProvider.java:102)
	at fr.opensagres.poi.xwpf.converter.core.styles.AbstractValueProvider.internalGetValue(AbstractValueProvider.java:62)
	at fr.opensagres.poi.xwpf.converter.core.styles.AbstractValueProvider.getValue(AbstractValueProvider.java:42)
	at fr.opensagres.poi.xwpf.converter.core.styles.XWPFStylesDocument.getTableCellVMerge(XWPFStylesDocument.java:1091)
	at fr.opensagres.poi.xwpf.converter.core.XWPFDocumentVisitor.getVMergedCells(XWPFDocumentVisitor.java:1154)
	at fr.opensagres.poi.xwpf.converter.core.XWPFDocumentVisitor.visitTableRow(XWPFDocumentVisitor.java:1070)
	at fr.opensagres.poi.xwpf.converter.core.XWPFDocumentVisitor.visitTableBody(XWPFDocumentVisitor.java:990)
	at fr.opensagres.poi.xwpf.converter.core.XWPFDocumentVisitor.visitTable(XWPFDocumentVisitor.java:972)
	at fr.opensagres.poi.xwpf.converter.core.XWPFDocumentVisitor.visitBodyElements(XWPFDocumentVisitor.java:267)
	at fr.opensagres.poi.xwpf.converter.core.XWPFDocumentVisitor.start(XWPFDocumentVisitor.java:215)
	at fr.opensagres.poi.xwpf.converter.pdf.PdfConverter.doConvert(PdfConverter.java:65)
	... 29 more`

**Comment by angelozerr** [comment]
Without your docx, and Java main,it's hard to help you.
