### ISSUE TITLE
java.lang.NoClassDefFoundError: org/bouncycastle/asn1/ASN1OctetString

### ISSUE THREAD

**Issue by felixruponen** [opensagres/xdocreport#50]
When trying to encrypt pdf using PDFWriter the following error is thrown:

at com.lowagie.text.pdf.PdfEncryption.<init>(Unknown Source)
	at com.lowagie.text.pdf.PdfWriter.setEncryption(Unknown Source)
	at se.newseed.pdfservice.PdfService$PdfServiceThread$1.configure(PdfService.java:260)
	at fr.opensagres.xdocreport.itext.extension.ExtendedDocument.<init>(ExtendedDocument.java:64)
	at org.odftoolkit.odfdom.converter.pdf.internal.stylable.StylableDocument.<init>(StylableDocument.java:76)
	at org.odftoolkit.odfdom.converter.pdf.internal.ElementVisitorForIText.<init>(ElementVisitorForIText.java:148)
	at org.odftoolkit.odfdom.converter.pdf.PdfConverter.processBody(PdfConverter.java:114)
	at org.odftoolkit.odfdom.converter.pdf.PdfConverter.doConvert(PdfConverter.java:65)
	at org.odftoolkit.odfdom.converter.pdf.PdfConverter.doConvert(PdfConverter.java:43)
	at org.odftoolkit.odfdom.converter.core.AbstractODFConverter.convert(AbstractODFConverter.java:42)
	at fr.opensagres.xdocreport.converter.odt.odfdom.itext.ODF2PDFViaITextConverter.convert(ODF2PDFViaITextConverter.java:62)
	at fr.opensagres.xdocreport.document.AbstractXDocReport.convert(AbstractXDocReport.java:713)
	... 2 more
Caused by: java.lang.ClassNotFoundException: org.bouncycastle.asn1.ASN1OctetString
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 14 more

This stackOverFlow thread explains that backward compatibility issues with iText exists with newer versions of the BouncyCastle libraries

http://stackoverflow.com/questions/10391271/itext-bouncycastle-classnotfound-org-bouncycastle-asn1-derencodable-and-org-boun

Is there anyway that I can use a lower version of bounty castle?

**Comment by felixruponen** [comment]
Adding this dependency to maven resolved this issue for me:

<dependency>
      <groupId>org.bouncycastle</groupId>
      <artifactId>bcprov-jdk15</artifactId>
     <version>1.44</version>
</dependency>

This only works for the ODT converter though.

**Comment by angelozerr** [comment]
@felixruponen can we close this issue?

**Comment by felixruponen** [comment]
Sure!
