### ISSUE TITLE
.odt table won't work

### ISSUE THREAD

**Issue by dwori** [opensagres/xdocreport#545]
I tried to rebuild the sample from the documentation, but when i try to create tables or fill them. It always fails due to the follwing error. I cannot figure out what the issue is...

ERROR:
```
Apr. 12, 2022 10:21:05 VORM. freemarker.log._JULLoggerFactory$JULLogger error
SEVERE: Error executing FreeMarker template
FreeMarker template error:
The following has evaluated to null or missing:
==> devs.name  [in template "fr.opensagres.xdocreport.document.odt.ODTReport@57855c9a!content.xml" at line 5, column 11]

----
Tip: It's the step after the last dot that caused this error, not those before it.
----
Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use [#if myOptionalVar??]when-present[#else]when-missing[/#if]. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
----

----
FTL stack trace ("~" means nesting-related):
	- Failed at: ${devs.name} auto-escaped  [in template "fr.opensagres.xdocreport.document.odt.ODTReport@57855c9a!content.xml" at line 5, column 9]
----

Java stack trace (for programmers):
----
freemarker.core.InvalidReferenceException: [... Exception message was already printed; see it above ...]
	at freemarker.core.InvalidReferenceException.getInstance(InvalidReferenceException.java:134)
	at freemarker.core.EvalUtil.coerceModelToTextualCommon(EvalUtil.java:481)
	at freemarker.core.EvalUtil.coerceModelToStringOrMarkup(EvalUtil.java:401)
	at freemarker.core.EvalUtil.coerceModelToStringOrMarkup(EvalUtil.java:370)
	at freemarker.core.BuiltInForLegacyEscaping._eval(BuiltInForLegacyEscaping.java:34)
	at freemarker.core.Expression.eval(Expression.java:101)
	at freemarker.core.Expression.evalAndCoerceToStringOrUnsupportedMarkup(Expression.java:139)
	at freemarker.core.BuiltInForString.getTargetString(BuiltInForString.java:34)
	at freemarker.core.BuiltInForString._eval(BuiltInForString.java:29)
	at freemarker.core.Expression.eval(Expression.java:101)
	at freemarker.core.MethodCall._eval(MethodCall.java:55)
	at freemarker.core.Expression.eval(Expression.java:101)
	at freemarker.core.Expression.evalAndCoerceToStringOrUnsupportedMarkup(Expression.java:139)
	at freemarker.core.BuiltInForString.getTargetString(BuiltInForString.java:34)
	at freemarker.core.BuiltInForString._eval(BuiltInForString.java:29)
	at freemarker.core.Expression.eval(Expression.java:101)
	at freemarker.core.MethodCall._eval(MethodCall.java:55)
	at freemarker.core.Expression.eval(Expression.java:101)
	at freemarker.core.Expression.evalAndCoerceToStringOrUnsupportedMarkup(Expression.java:139)
	at freemarker.core.BuiltInForString.getTargetString(BuiltInForString.java:34)
	at freemarker.core.BuiltInForString._eval(BuiltInForString.java:29)
	at freemarker.core.Expression.eval(Expression.java:101)
	at freemarker.core.MethodCall._eval(MethodCall.java:55)
	at freemarker.core.Expression.eval(Expression.java:101)
	at freemarker.core.DollarVariable.calculateInterpolatedStringOrMarkup(DollarVariable.java:100)
	at freemarker.core.DollarVariable.accept(DollarVariable.java:63)
	at freemarker.core.Environment.visit(Environment.java:383)
	at freemarker.core.IteratorBlock$IterationContext.executedNestedContentForCollOrSeqListing(IteratorBlock.java:321)
	at freemarker.core.IteratorBlock$IterationContext.executeNestedContent(IteratorBlock.java:271)
	at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:244)
	at freemarker.core.Environment.visitIteratorBlock(Environment.java:657)
	at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:108)
	at freemarker.core.IteratorBlock.accept(IteratorBlock.java:94)
	at freemarker.core.Environment.visit(Environment.java:347)
	at freemarker.core.Environment.visit(Environment.java:353)
	at freemarker.core.Environment.visit(Environment.java:353)
	at freemarker.core.Environment.process(Environment.java:326)
	at fr.opensagres.xdocreport.template.freemarker.FreemarkerTemplateEngine.process(FreemarkerTemplateEngine.java:163)
	at fr.opensagres.xdocreport.template.freemarker.FreemarkerTemplateEngine.processNoCache(FreemarkerTemplateEngine.java:122)
	at fr.opensagres.xdocreport.template.AbstractTemplateEngine.process(AbstractTemplateEngine.java:118)
	at fr.opensagres.xdocreport.template.AbstractTemplateEngine.process(AbstractTemplateEngine.java:83)
	at fr.opensagres.xdocreport.document.AbstractXDocReport.processTemplateEngine(AbstractXDocReport.java:772)
	at fr.opensagres.xdocreport.document.AbstractXDocReport.process(AbstractXDocReport.java:518)
	at fr.opensagres.xdocreport.document.AbstractXDocReport.process(AbstractXDocReport.java:484)
	at report_creation.fillList.main(fillList.java:51)
```

>I am currently using this code:

fillList.java

```java
public class fillList {
    public static void main(String[] args) {
        try {
            // 1) Load ODT file by filling Velocity template engine and cache
            // it to the registry
            InputStream in = fillList.class.getResourceAsStream("Test.odt");
            IXDocReport report = XDocReportRegistry.getRegistry().loadReport(in, TemplateEngineKind.Freemarker);

            // 2) Create fields metadata to manage lazy loop (#foreach velocity)
            // for table row.
            FieldsMetadata metadata = new FieldsMetadata();
            metadata.addFieldAsList("developers.name");
            metadata.addFieldAsList("developers.lastName");
            metadata.addFieldAsList("developers.mail");
            report.setFieldsMetadata(metadata);

            // 3) Create context Java model
            IContext context = report.createContext();
            Project project = new Project("Create Dynamic Reports", 101);
            context.put("project", project);

            // Register developers list
            List<Developer> developers = new ArrayList<>();
            developers.add(new Developer("ZERR", "Angelo", "angelo.zerr@gmail.com"));
            developers.add(new Developer("Leclercq", "Pascal", "pascal.leclercq@gmail.com"));
            context.put("developers", developers);

            // 4) Generate report by merging Java model with the ODT
            OutputStream out = new FileOutputStream(new File("Test2_out.odt"));
            report.process(context, out);
            System.out.println("Report creation successfully completed!");

        } catch (IOException e) {
            System.err.println("[Debug Assistent]: No report created! >> IOException");
            e.printStackTrace();
        } catch (XDocReportException e) {
            System.err.println("[Debug Assistent]: No report created! >> XDocReportException");
            e.printStackTrace();
        }
    }
}
```
Project.java

```java
public class Project {

    private final String name;
    private final Integer ID;

    public Project(String name, Integer id) {
        this.name = name;
        this.ID = id;
    }

    public String getName() {
        return name;
    }

    public Integer getID() {
        return ID;
    }
}
```

Developer.java

```java
public class Developer {

    private final String name;
    private final String lastName;
    private final String mail;

    public Developer(String name, String lastName, String mail) {
        this.name = name;
        this.lastName = lastName;
        this.mail = mail;
    }

    public String getFirstName() {
        return name;
    }

    public String getLastName() {
        return lastName;
    }

    public String getMail() {
        return mail;
    }
}
```

This is the .odt file i am using.
![odttable](https://user-images.githubusercontent.com/73217570/162918767-b7b9b366-8ab8-437b-b860-8af18a3fa930.PNG)

**Comment by angelozerr** [comment]
Thats strange your template doesnt contains devs.name

Coud you try to remove the fieldsmetadata code

**Comment by dwori** [comment]
I tried without the developer model too. With the removed fieldsmetadata code i get another error.

fillList.java

```java
public class fillList {

    public static void main(String[] args) {
        try {
            // 1) Load ODT file by filling Velocity template engine and cache
            // it to the registry
            InputStream in = fillList.class.getResourceAsStream("Test3.odt");
            IXDocReport report = XDocReportRegistry.getRegistry().loadReport(in, TemplateEngineKind.Freemarker);

            // 2) Create fields metadata to manage lazy loop (#foreach velocity)
            // for table row.
            //            FieldsMetadata metadata = new FieldsMetadata();
            //            metadata.addFieldAsList("developers.name");
            //            metadata.addFieldAsList("developers.lastName");
            //            metadata.addFieldAsList("developers.mail");
            //            report.setFieldsMetadata(metadata);

            // 3) Create context Java model
            IContext context = report.createContext();
            Project project = new Project("Create Dynamic Reports", 101);
            context.put("project", project);

            // Register developers list
            //            List<Developer> developers = new ArrayList<>();
            //            developers.add(new Developer("ZERR", "Angelo", "angelo.zerr@gmail.com"));
            //            developers.add(new Developer("Leclercq", "Pascal", "pascal.leclercq@gmail.com"));
            //            context.put("developers", developers);

            List<Developer> developers = new ArrayList<>();

            developers.add(new Developer("ZERR", "Angelo", "angelo.zerr@gmail.com"));

            developers.add(new Developer("Leclercq", "Pascal", "pascal.leclercq@gmail.com"));

            developers.add(new Developer("Bousta", "Amine", ""));

            context.put("developers", developers);

            // 4) Generate report by merging Java model with the ODT
            OutputStream out = new FileOutputStream(new File("Test3_out.odt"));
            report.process(context, out);
            System.out.println("Report creation successfully completed!");

        } catch (IOException e) {
            System.err.println("[Debug Assistent]: No report created! >> IOException");
            e.printStackTrace();
        } catch (XDocReportException e) {
            System.err.println("[Debug Assistent]: No report created! >> XDocReportException");
            e.printStackTrace();
        }
    }
}
```

Error:

```
[Debug Assistent]: No report created! >> IOException
freemarker.core.ParseException: Syntax error in template "fr.opensagres.xdocreport.document.odt.ODTReport@4f063c0a!content.xml" in line 5, column 142:
Encountered "[/#escape]", but at this place only this can be closed: "#list". This usually because of wrong nesting of FreeMarker directives, like a missed or malformed end-tag somewhere. (Note that FreeMarker end-tags must have # or @ after the / character.)
Was expecting one of these patterns:
    <ATTEMPT>
    <IF>
    <LIST>
    <ITEMS>
    <SEP>
    <FOREACH>
    <SWITCH>
    <ASSIGN>
    <GLOBALASSIGN>
    <LOCALASSIGN>
    <_INCLUDE>
    <IMPORT>
    <FUNCTION>
    <MACRO>
    <TRANSFORM>
    <VISIT>
    <STOP>
    <RETURN>
    <CALL>
    <SETTING>
    <OUTPUTFORMAT>
    <AUTOESC>
    <NOAUTOESC>
    <COMPRESS>
    <COMMENT>
    <TERSE_COMMENT>
    <NOPARSE>
    <END_LIST>
    <ELSE>
    <BREAK>
    <CONTINUE>
    <SIMPLE_RETURN>
    <HALT>
    <FLUSH>
    <TRIM>
    <LTRIM>
    <RTRIM>
    <NOTRIM>
    <SIMPLE_NESTED>
    <NESTED>
    <SIMPLE_RECURSE>
    <RECURSE>
    <FALLBACK>
    <ESCAPE>
    <NOESCAPE>
    <UNIFIED_CALL>
    <STATIC_TEXT_WS>
    <STATIC_TEXT_NON_WS>
    <STATIC_TEXT_FALSE_ALARM>
    "${"
    "#{"
    "[="
	at freemarker.core.FMParser.generateParseException(FMParser.java:6120)
	at freemarker.core.FMParser.jj_consume_token(FMParser.java:5979)
	at freemarker.core.FMParser.List(FMParser.java:1932)
	at freemarker.core.FMParser.FreemarkerDirective(FMParser.java:3633)
	at freemarker.core.FMParser.MixedContentElements(FMParser.java:4019)
	at freemarker.core.FMParser.Escape(FMParser.java:3443)
	at freemarker.core.FMParser.FreemarkerDirective(FMParser.java:3735)
	at freemarker.core.FMParser.MixedContentElements(FMParser.java:4019)
	at freemarker.core.FMParser.Root(FMParser.java:4665)
	at freemarker.template.Template.<init>(Template.java:252)
	at freemarker.template.Template.<init>(Template.java:202)
	at freemarker.template.Template.<init>(Template.java:181)
	at freemarker.template.Template.<init>(Template.java:124)
	at fr.opensagres.xdocreport.template.freemarker.FreemarkerTemplateEngine.processNoCache(FreemarkerTemplateEngine.java:120)
	at fr.opensagres.xdocreport.template.AbstractTemplateEngine.process(AbstractTemplateEngine.java:118)
	at fr.opensagres.xdocreport.template.AbstractTemplateEngine.process(AbstractTemplateEngine.java:83)
	at fr.opensagres.xdocreport.document.AbstractXDocReport.processTemplateEngine(AbstractXDocReport.java:772)
	at fr.opensagres.xdocreport.document.AbstractXDocReport.process(AbstractXDocReport.java:518)
	at fr.opensagres.xdocreport.document.AbstractXDocReport.process(AbstractXDocReport.java:484)
	at report_creation.fillList.main(fillList.java:65)
```

**Comment by dwori** [comment]
Or did you want me to edit it like this?

```java
public class fillList {

    public static void main(String[] args) {
        try {
            // 1) Load ODT file by filling Velocity template engine and cache
            // it to the registry
            InputStream in = fillList.class.getResourceAsStream("Test2.odt");
            IXDocReport report = XDocReportRegistry.getRegistry().loadReport(in, TemplateEngineKind.Freemarker);

            // 2) Create fields metadata to manage lazy loop (#foreach velocity)
            // for table row.
            //            FieldsMetadata metadata = new FieldsMetadata();
            //            metadata.addFieldAsList("developers.name");
            //            metadata.addFieldAsList("developers.lastName");
            //            metadata.addFieldAsList("developers.mail");
            //            report.setFieldsMetadata(metadata);

            // 3) Create context Java model
            IContext context = report.createContext();
            Project project = new Project("Create Dynamic Reports", 101);
            context.put("project", project);

            // Register developers list
            List<Developer> developers = new ArrayList<>();
            developers.add(new Developer("ZERR", "Angelo", "angelo.zerr@gmail.com"));
            developers.add(new Developer("Leclercq", "Pascal", "pascal.leclercq@gmail.com"));
            context.put("developers", developers);

            //            List<Developer> developers = new ArrayList<>();
            //
            //            developers.add(new Developer("ZERR", "Angelo", "angelo.zerr@gmail.com"));
            //
            //            developers.add(new Developer("Leclercq", "Pascal", "pascal.leclercq@gmail.com"));
            //
            //            developers.add(new Developer("Bousta", "Amine", ""));
            //
            //            context.put("developers", developers);

            // 4) Generate report by merging Java model with the ODT
            OutputStream out = new FileOutputStream(new File("Test2_out.odt"));
            report.process(context, out);
            System.out.println("Report creation successfully completed!");

        } catch (IOException e) {
            System.err.println("[Debug Assistent]: No report created! >> IOException");
            e.printStackTrace();
        } catch (XDocReportException e) {
            System.err.println("[Debug Assistent]: No report created! >> XDocReportException");
            e.printStackTrace();
        }
    }
}
```

Error:

```
Apr. 12, 2022 2:20:41 NACHM. freemarker.log._JULLoggerFactory$JULLogger error
SEVERE: Error executing FreeMarker template
FreeMarker template error:
The following has evaluated to null or missing:
==> devs.name  [in template "fr.opensagres.xdocreport.document.odt.ODTReport@4f063c0a!content.xml" at line 5, column 11]

----
Tip: It's the step after the last dot that caused this error, not those before it.
----
Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use [#if myOptionalVar??]when-present[#else]when-missing[/#if]. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
----

----
FTL stack trace ("~" means nesting-related):
	- Failed at: ${devs.name} auto-escaped  [in template "fr.opensagres.xdocreport.document.odt.ODTReport@4f063c0a!content.xml" at line 5, column 9]
----

Java stack trace (for programmers):
----
freemarker.core.InvalidReferenceException: [... Exception message was already printed; see it above ...]
	at freemarker.core.InvalidReferenceException.getInstance(InvalidReferenceException.java:134)
	at freemarker.core.EvalUtil.coerceModelToTextualCommon(EvalUtil.java:481)
	at freemarker.core.EvalUtil.coerceModelToStringOrMarkup(EvalUtil.java:401)
	at freemarker.core.EvalUtil.coerceModelToStringOrMarkup(EvalUtil.java:370)
	at freemarker.core.BuiltInForLegacyEscaping._eval(BuiltInForLegacyEscaping.java:34)
	at freemarker.core.Expression.eval(Expression.java:101)
	at freemarker.core.Expression.evalAndCoerceToStringOrUnsupportedMarkup(Expression.java:139)
	at freemarker.core.BuiltInForString.getTargetString(BuiltInForString.java:34)
	at freemarker.core.BuiltInForString._eval(BuiltInForString.java:29)
	at freemarker.core.Expression.eval(Expression.java:101)
	at freemarker.core.MethodCall._eval(MethodCall.java:55)
	at freemarker.core.Expression.eval(Expression.java:101)
	at freemarker.core.Expression.evalAndCoerceToStringOrUnsupportedMarkup(Expression.java:139)
	at freemarker.core.BuiltInForString.getTargetString(BuiltInForString.java:34)
	at freemarker.core.BuiltInForString._eval(BuiltInForString.java:29)
	at freemarker.core.Expression.eval(Expression.java:101)
	at freemarker.core.MethodCall._eval(MethodCall.java:55)
	at freemarker.core.Expression.eval(Expression.java:101)
	at freemarker.core.Expression.evalAndCoerceToStringOrUnsupportedMarkup(Expression.java:139)
	at freemarker.core.BuiltInForString.getTargetString(BuiltInForString.java:34)
	at freemarker.core.BuiltInForString._eval(BuiltInForString.java:29)
	at freemarker.core.Expression.eval(Expression.java:101)
	at freemarker.core.MethodCall._eval(MethodCall.java:55)
	at freemarker.core.Expression.eval(Expression.java:101)
	at freemarker.core.DollarVariable.calculateInterpolatedStringOrMarkup(DollarVariable.java:100)
	at freemarker.core.DollarVariable.accept(DollarVariable.java:63)
	at freemarker.core.Environment.visit(Environment.java:383)
	at freemarker.core.IteratorBlock$IterationContext.executedNestedContentForCollOrSeqListing(IteratorBlock.java:321)
	at freemarker.core.IteratorBlock$IterationContext.executeNestedContent(IteratorBlock.java:271)
	at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:244)
	at freemarker.core.Environment.visitIteratorBlock(Environment.java:657)
	at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:108)
	at freemarker.core.IteratorBlock.accept(IteratorBlock.java:94)
	at freemarker.core.Environment.visit(Environment.java:347)
	at freemarker.core.Environment.visit(Environment.java:353)
	at freemarker.core.Environment.visit(Environment.java:353)
	at freemarker.core.Environment.process(Environment.java:326)
	at fr.opensagres.xdocreport.template.freemarker.FreemarkerTemplateEngine.process(FreemarkerTemplateEngine.java:163)
	at fr.opensagres.xdocreport.template.freemarker.FreemarkerTemplateEngine.processNoCache(FreemarkerTemplateEngine.java:122)
	at fr.opensagres.xdocreport.template.AbstractTemplateEngine.process(AbstractTemplateEngine.java:118)
	at fr.opensagres.xdocreport.template.AbstractTemplateEngine.process(AbstractTemplateEngine.java:83)
	at fr.opensagres.xdocreport.document.AbstractXDocReport.processTemplateEngine(AbstractXDocReport.java:772)
	at fr.opensagres.xdocreport.document.AbstractXDocReport.process(AbstractXDocReport.java:518)
	at fr.opensagres.xdocreport.document.AbstractXDocReport.process(AbstractXDocReport.java:484)
	at report_creation.fillList.main(fillList.java:65)

[Debug Assistent]: No report created! >> XDocReportException
fr.opensagres.xdocreport.core.XDocReportException: freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
==> devs.name  [in template "fr.opensagres.xdocreport.document.odt.ODTReport@4f063c0a!content.xml" at line 5, column 11]

----
Tip: It's the step after the last dot that caused this error, not those before it.
----
Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use [#if myOptionalVar??]when-present[#else]when-missing[/#if]. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
----

----
FTL stack trace ("~" means nesting-related):
	- Failed at: ${devs.name} auto-escaped  [in template "fr.opensagres.xdocreport.document.odt.ODTReport@4f063c0a!content.xml" at line 5, column 9]
----
	at fr.opensagres.xdocreport.template.freemarker.FreemarkerTemplateEngine.process(FreemarkerTemplateEngine.java:167)
	at fr.opensagres.xdocreport.template.freemarker.FreemarkerTemplateEngine.processNoCache(FreemarkerTemplateEngine.java:122)
	at fr.opensagres.xdocreport.template.AbstractTemplateEngine.process(AbstractTemplateEngine.java:118)
	at fr.opensagres.xdocreport.template.AbstractTemplateEngine.process(AbstractTemplateEngine.java:83)
	at fr.opensagres.xdocreport.document.AbstractXDocReport.processTemplateEngine(AbstractXDocReport.java:772)
	at fr.opensagres.xdocreport.document.AbstractXDocReport.process(AbstractXDocReport.java:518)
	at fr.opensagres.xdocreport.document.AbstractXDocReport.process(AbstractXDocReport.java:484)
	at report_creation.fillList.main(fillList.java:65)
Caused by: freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
==> devs.name  [in template "fr.opensagres.xdocreport.document.odt.ODTReport@4f063c0a!content.xml" at line 5, column 11]

----
Tip: It's the step after the last dot that caused this error, not those before it.
----
Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use [#if myOptionalVar??]when-present[#else]when-missing[/#if]. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
----

----
FTL stack trace ("~" means nesting-related):
	- Failed at: ${devs.name} auto-escaped  [in template "fr.opensagres.xdocreport.document.odt.ODTReport@4f063c0a!content.xml" at line 5, column 9]
----
	at freemarker.core.InvalidReferenceException.getInstance(InvalidReferenceException.java:134)
	at freemarker.core.EvalUtil.coerceModelToTextualCommon(EvalUtil.java:481)
	at freemarker.core.EvalUtil.coerceModelToStringOrMarkup(EvalUtil.java:401)
	at freemarker.core.EvalUtil.coerceModelToStringOrMarkup(EvalUtil.java:370)
	at freemarker.core.BuiltInForLegacyEscaping._eval(BuiltInForLegacyEscaping.java:34)
	at freemarker.core.Expression.eval(Expression.java:101)
	at freemarker.core.Expression.evalAndCoerceToStringOrUnsupportedMarkup(Expression.java:139)
	at freemarker.core.BuiltInForString.getTargetString(BuiltInForString.java:34)
	at freemarker.core.BuiltInForString._eval(BuiltInForString.java:29)
	at freemarker.core.Expression.eval(Expression.java:101)
	at freemarker.core.MethodCall._eval(MethodCall.java:55)
	at freemarker.core.Expression.eval(Expression.java:101)
	at freemarker.core.Expression.evalAndCoerceToStringOrUnsupportedMarkup(Expression.java:139)
	at freemarker.core.BuiltInForString.getTargetString(BuiltInForString.java:34)
	at freemarker.core.BuiltInForString._eval(BuiltInForString.java:29)
	at freemarker.core.Expression.eval(Expression.java:101)
	at freemarker.core.MethodCall._eval(MethodCall.java:55)
	at freemarker.core.Expression.eval(Expression.java:101)
	at freemarker.core.Expression.evalAndCoerceToStringOrUnsupportedMarkup(Expression.java:139)
	at freemarker.core.BuiltInForString.getTargetString(BuiltInForString.java:34)
	at freemarker.core.BuiltInForString._eval(BuiltInForString.java:29)
	at freemarker.core.Expression.eval(Expression.java:101)
	at freemarker.core.MethodCall._eval(MethodCall.java:55)
	at freemarker.core.Expression.eval(Expression.java:101)
	at freemarker.core.DollarVariable.calculateInterpolatedStringOrMarkup(DollarVariable.java:100)
	at freemarker.core.DollarVariable.accept(DollarVariable.java:63)
	at freemarker.core.Environment.visit(Environment.java:383)
	at freemarker.core.IteratorBlock$IterationContext.executedNestedContentForCollOrSeqListing(IteratorBlock.java:321)
	at freemarker.core.IteratorBlock$IterationContext.executeNestedContent(IteratorBlock.java:271)
	at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:244)
	at freemarker.core.Environment.visitIteratorBlock(Environment.java:657)
	at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:108)
	at freemarker.core.IteratorBlock.accept(IteratorBlock.java:94)
	at freemarker.core.Environment.visit(Environment.java:347)
	at freemarker.core.Environment.visit(Environment.java:353)
	at freemarker.core.Environment.visit(Environment.java:353)
	at freemarker.core.Environment.process(Environment.java:326)
	at fr.opensagres.xdocreport.template.freemarker.FreemarkerTemplateEngine.process(FreemarkerTemplateEngine.java:163)
	... 7 more
```

**Comment by angelozerr** [comment]
I m sorry it was à long time that I did that and I dont understand why it doesnt work.

Today I have no time to work on XDocReport.

Any contribution are welcome.

**Comment by angelozerr** [comment]
In your screenshot I dont see ${devs.name} which causes the problem.

Are you sure that you have not this declaration in the odt?

**Comment by dwori** [comment]
Yes I am sure, I also tried it with developers as d, like in the samples but the same error occurred, but with d.name this time.

**Comment by dwori** [comment]
Fixed it. Nevertheless thanks for the help.

**Comment by angelozerr** [comment]
What was the problem?

**Comment by dwori** [comment]
There was a typo in the Developer class. which lead to not matching model and template.

**Comment by angelozerr** [comment]
This typo comes from the doc?

**Comment by dwori** [comment]
No, it was actually in the Java Model class.

The getter was:

```java
public String getFirstName() {
        return name;
    }
```
But should have been:
```java
public String getName() {
        return name;
    }
```

**Comment by snake-zhiqiang** [comment]
i also hava this problem.After i checked,there is no typo in the entity.

**Comment by snake-zhiqiang** [comment]
it don't work in prod.but it is working in the develop env.

**Comment by snake-zhiqiang** [comment]
@angelozerr
