### ISSUE TITLE
Class not found exception while trying to convert report to PDF

### ISSUE THREAD

**Issue by mohamnag** [opensagres/xdocreport#57]
I'm trying to use the last code on [this](https://github.com/opensagres/xdocreport/wiki/DocxReportingJavaMainConverter) page to generate a PDF out of the report.
I know that report generation is successful because I can save the doc as XDoc and it works fine. However when I try to save it as PDF I get following output:

```
fr.opensagres.xdocreport.converter.XDocConverterException: java.lang.NoClassDefFoundError: org/apache/poi/xwpf/usermodel/IRunBody
	at fr.opensagres.xdocreport.document.AbstractXDocReport.convert(AbstractXDocReport.java:748)
	at XdocVelocityMap.main(XdocVelocityMap.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: java.lang.NoClassDefFoundError: org/apache/poi/xwpf/usermodel/IRunBody
	at org.apache.poi.xwpf.converter.pdf.PdfConverter.doConvert(PdfConverter.java:55)
	at org.apache.poi.xwpf.converter.pdf.PdfConverter.doConvert(PdfConverter.java:38)
	at org.apache.poi.xwpf.converter.core.AbstractXWPFConverter.convert(AbstractXWPFConverter.java:45)
	at fr.opensagres.xdocreport.converter.docx.poi.itext.XWPF2PDFViaITextConverter.convert(XWPF2PDFViaITextConverter.java:67)
	at fr.opensagres.xdocreport.document.AbstractXDocReport.convert(AbstractXDocReport.java:713)
	... 6 more
Caused by: java.lang.ClassNotFoundException: org.apache.poi.xwpf.usermodel.IRunBody
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 11 more
```

these are my defined dependencies:
<img width="420" alt="screen shot 2015-08-04 at 23 56 44" src="https://cloud.githubusercontent.com/assets/4481421/9073880/ef87cc86-3b04-11e5-8ac5-00ec0efed125.png">

any idea what could be missing?

**Comment by angelozerr** [comment]
It's a problem with POI, please post your question to POI forum.

**Comment by mohamnag** [comment]
looking at the stack trace of the exception, it seems more to me that it is an undefined dependency of package `org.apache.poi.xwpf.converter.pdf` which is one of the XDocReport packages not POI:

```
java.lang.NoClassDefFoundError: org/apache/poi/xwpf/usermodel/IRunBody
	at org.apache.poi.xwpf.converter.pdf.PdfConverter.doConvert(PdfConverter.java:55)
	at org.apache.poi.xwpf.converter.pdf.PdfConverter.doConvert(PdfConverter.java:38)
	at org.apache.poi.xwpf.converter.core.AbstractXWPFConverter.convert(AbstractXWPFConverter.java:45)
	at fr.opensagres.xdocreport.converter.docx.poi.itext.XWPF2PDFViaITextConverter.convert(XWPF2PDFViaITextConverter.java:67)
	at fr.opensagres.xdocreport.document.AbstractXDocReport.convert(AbstractXDocReport.java:713)
	at XdocVelocityMap.main(XdocVelocityMap.java:48)
Caused by: java.lang.ClassNotFoundException: org.apache.poi.xwpf.usermodel.IRunBody
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 6 more
```

unfortunately XDocReport maven packages miss lots of such dependency definitions.

**Comment by mohamnag** [comment]
as I suspected the problem was wrong dependency, the docs say poi-ooxml v 3.9 but the code needs at least v 3.10.1, I used 3.11 successfully. so I would also update the docs

**Comment by angelozerr** [comment]
Doc is out of date for the version. I think it's a bad idea to set the version in the doc, because we  must synch the doc with maven pom. I think it's better to set a link to the pom to know the version of POI

**Comment by mohamnag** [comment]
Actually a proper maven definition includes all the dependencies a package needs, so this (and all other packages needed) should have been a defined dependency of one of XDocReport packages which implements main Docx to PDF conversion.
