### ISSUE TITLE
Multithreading problem

### ISSUE THREAD

**Issue by giorgiogiustiniani** [opensagres/xdocreport#59]
Hi,I'm converting odt to pdf with a multithread application 10-20 thread

I'm using 1.0.5 on windows 7 64 bit with these libraries

org.odftoolkit.odfdom.converter.pdf-1.0.5.jar
org.odftoolkit.odfdom.converter.core-1.0.5.jar
fr.opensagres.xdocreport.itext.extension-1.0.5.jar
itext 2.1.7
odfdom-java-0.8.7.jar
xercesImpl-2.9.1.jar
xml-apis-1.3.04.jar

Hi receive this exception,something seems non thread safe:

rg.odftoolkit.odfdom.converter.core.ODFConverterException: java.util.ConcurrentModificationException
	at org.odftoolkit.odfdom.converter.pdf.PdfConverter.doConvert(PdfConverter.java:82)
	at org.odftoolkit.odfdom.converter.pdf.PdfConverter.doConvert(PdfConverter.java:43)
	at org.odftoolkit.odfdom.converter.core.AbstractODFConverter.convert(AbstractODFConverter.java:42)
	at fr.opensagres.xdocreport.samples.odt.converters.pdf.TestConverter.convert(TestConverter.java:67)
	at fr.opensagres.xdocreport.samples.odt.converters.pdf.MultiThreadManipolationRunnerDocX.run(MultiThreadManipolationRunnerDocX.java:65)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at com.lowagie.text.FontFactoryImp.getFont(Unknown Source)
	at com.lowagie.text.FontFactoryImp.getFont(Unknown Source)
	at com.lowagie.text.FontFactory.getFont(Unknown Source)
	at com.lowagie.text.FontFactory.getFont(Unknown Source)
	at fr.opensagres.xdocreport.itext.extension.font.AbstractFontRegistry.getFont(AbstractFontRegistry.java:53)

**Comment by angelozerr** [comment]
It seems that it's a problem with iText 2.1.7

No time to study the problem -(

**Comment by blagae** [comment]
There were known concurrency issues in iText 2.1.7. There are fixes which have been done in iText 5.x (the changelog mentions threading/synchronization/concurrency in 5.1.2, 5.4.0, 5.4.2, and 5.5.6), but of course these are under the more restrictive AGPL license.

I also don't know if your issue would be fixed by switching to iText 5, but most of the problems fixed in newer versions are related to the Font implementation.

**Comment by angelozerr** [comment]
Thanks @blagae for your information.

We have an implementation of converter with iText 5.* too. Please try it but pay attention iText 5* has not the same license than 2.1.7
