### ISSUE TITLE
Not compatible with OpenPDF 2.0.0 - Runtime error: NoSuchMethodError void fr.opensagres.poi.xwpf.converter.pdf.internal.elements.StylableDocumentSection$SectionPdfPTable.addCell

### ISSUE THREAD

**Issue by henricook** [opensagres/xdocreport#635]
In OpenPDF 2.0.0 a method signature changed, which prevents it being used with xdocreport. This method now returns a cell instead of `void`:

```
[info]   java.lang.NoSuchMethodError: 'void fr.opensagres.poi.xwpf.converter.pdf.internal.elements.StylableDocumentSection$SectionPdfPTable.addCell(com.lowagie.text.pdf.PdfPCell)'
[info]   at fr.opensagres.poi.xwpf.converter.pdf.internal.elements.StylableDocumentSection.createLayoutTable(StylableDocumentSection.java:424)
[info]   at fr.opensagres.poi.xwpf.converter.pdf.internal.elements.StylableDocumentSection.createLayoutTable(StylableDocumentSection.java:401)
[info]   at fr.opensagres.poi.xwpf.converter.pdf.internal.elements.StylableDocument.setActiveMasterPage(StylableDocument.java:318)
[info]   at fr.opensagres.poi.xwpf.converter.pdf.internal.PdfMapper.setActiveMasterPage(PdfMapper.java:254)
[info]   at fr.opensagres.poi.xwpf.converter.pdf.internal.PdfMapper.setActiveMasterPage(PdfMapper.java:123)
[info]   at fr.opensagres.poi.xwpf.converter.core.MasterPageManager.fireSectionChanged(MasterPageManager.java:173)
[info]   at fr.opensagres.poi.xwpf.converter.core.MasterPageManager.initialize(MasterPageManager.java:102)
[info]   at fr.opensagres.poi.xwpf.converter.core.XWPFDocumentVisitor.visitBodyElements(XWPFDocumentVisitor.java:249)
[info]   at fr.opensagres.poi.xwpf.converter.core.XWPFDocumentVisitor.start(XWPFDocumentVisitor.java:216)
[info]   at fr.opensagres.poi.xwpf.converter.pdf.PdfConverter.doConvert(PdfConverter.java:57)
```

**Comment by angelozerr** [comment]
Any PR are welcome!

**Comment by DKPillo** [comment]
Hi All

As I was just struggling with the exact same problem I like to leave a note on what the solution was for me:

I simply had to switch from `fr.opensagres.xdocreport:fr.opensagres.poi.xwpf.converter.pdf:2.2.0` to `fr.opensagres.xdocreport:fr.opensagres.poi.xwpf.converter.pdf.openpdf:2.2.0` and everything was working as expected #facepalm
