### ISSUE TITLE
java heap space issue with xdocreport

### ISSUE THREAD

**Issue by premmasarani** [opensagres/xdocreport#88]
I'm using xdocreport in my web application facing following issue.

I have 800 field configured in docx report
and for each field java code returns 50 records
with these number of data results in a java.lang.OutOfMemoryError: Java heap space
With less number of records i'm not facing any issue.
Is there any way to overcome this issue?

**Comment by angelozerr** [comment]
Have you a stacktrace?

Is it this problems comes from when several report are generated or just for the first generated report? It your OutOfMemoryError comes from after several geenrated report, I suggeest you to use cached report (I don't know how you have implemented the use of IXDocReport in your webapp).

In other words, please give us more info.

**Comment by premmasarani** [comment]
It comes for the first generated report.
here is the stack trace : 
fr.opensagres.xdocreport.core.XDocReportException: java.lang.OutOfMemoryError: Java heap space
	at fr.opensagres.xdocreport.document.AbstractXDocReport.process(AbstractXDocReport.java:565)
	at fr.opensagres.xdocreport.document.AbstractXDocReport.process(AbstractXDocReport.java:484)
	at com.os.gfnactions.isheet.iSheetAction.geneRateReport(iSheetAction.java:1966)
	at com.os.gfnactions.isheet.iSheetAction.generateSheetDocReport(iSheetAction.java:1504)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.opensymphony.xwork2.DefaultActionInvocation.invokeAction(DefaultActionInvocation.java:450)
	at com.opensymphony.xwork2.DefaultActionInvocation.invokeActionOnly(DefaultActionInvocation.java:289)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:252)
	at com.opensymphony.xwork2.interceptor.ExceptionMappingInterceptor.intercept(ExceptionMappingInterceptor.java:189)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:246)
	at org.apache.struts2.interceptor.DeprecationInterceptor.intercept(DeprecationInterceptor.java:41)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:246)
	at org.apache.struts2.interceptor.debugging.DebuggingInterceptor.intercept(DebuggingInterceptor.java:256)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:246)
	at com.opensymphony.xwork2.interceptor.DefaultWorkflowInterceptor.doIntercept(DefaultWorkflowInterceptor.java:167)
	at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:98)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:246)
	at com.opensymphony.xwork2.validator.ValidationInterceptor.doIntercept(ValidationInterceptor.java:265)
	at org.apache.struts2.interceptor.validation.AnnotationValidationInterceptor.doIntercept(AnnotationValidationInterceptor.java:68)
	at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:98)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:246)
	at com.opensymphony.xwork2.interceptor.ConversionErrorInterceptor.intercept(ConversionErrorInterceptor.java:138)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:246)
	at com.opensymphony.xwork2.interceptor.ParametersInterceptor.doIntercept(ParametersInterceptor.java:249)
	at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:98)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:246)
	at com.opensymphony.xwork2.interceptor.ParametersInterceptor.doIntercept(ParametersInterceptor.java:249)
	at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:98)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:246)
	at com.opensymphony.xwork2.interceptor.StaticParametersInterceptor.intercept(StaticParametersInterceptor.java:191)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:246)
	at org.apache.struts2.interceptor.MultiselectInterceptor.intercept(MultiselectInterceptor.java:73)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:246)
	at org.apache.struts2.interceptor.CheckboxInterceptor.intercept(CheckboxInterceptor.java:91)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:246)
	at org.apache.struts2.interceptor.FileUploadInterceptor.intercept(FileUploadInterceptor.java:252)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:246)
	at com.opensymphony.xwork2.interceptor.ModelDrivenInterceptor.intercept(ModelDrivenInterceptor.java:100)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:246)
	at com.opensymphony.xwork2.interceptor.ScopedModelDrivenInterceptor.intercept(ScopedModelDrivenInterceptor.java:141)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:246)
	at com.opensymphony.xwork2.interceptor.ChainingInterceptor.intercept(ChainingInterceptor.java:145)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:246)
	at com.opensymphony.xwork2.interceptor.PrepareInterceptor.doIntercept(PrepareInterceptor.java:171)
	at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:98)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:246)
	at com.opensymphony.xwork2.interceptor.I18nInterceptor.intercept(I18nInterceptor.java:139)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:246)
	at org.apache.struts2.interceptor.ServletConfigInterceptor.intercept(ServletConfigInterceptor.java:164)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:246)
	at com.opensymphony.xwork2.interceptor.AliasInterceptor.intercept(AliasInterceptor.java:193)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:246)
	at com.opensymphony.xwork2.interceptor.ExceptionMappingInterceptor.intercept(ExceptionMappingInterceptor.java:189)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:246)
	at com.os.interceptor.GriffinSecurity.intercept(GriffinSecurity.java:86)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:246)
	at com.os.interceptor.Security.invoke(Security.java:128)
	at com.os.interceptor.Security.intercept(Security.java:864)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:246)
	at com.os.interceptor.VirusSecurityInterceptor.intercept(VirusSecurityInterceptor.java:41)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:246)
	at org.apache.struts2.interceptor.DeprecationInterceptor.intercept(DeprecationInterceptor.java:41)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:246)
	at com.opensymphony.xwork2.interceptor.ConversionErrorInterceptor.intercept(ConversionErrorInterceptor.java:138)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:246)
	at com.opensymphony.xwork2.interceptor.ParametersInterceptor.doIntercept(ParametersInterceptor.java:249)
	at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:98)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:246)
	at com.opensymphony.xwork2.interceptor.ParametersInterceptor.doIntercept(ParametersInterceptor.java:249)
	at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:98)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:246)
	at org.apache.struts2.interceptor.MultiselectInterceptor.intercept(MultiselectInterceptor.java:73)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:246)
	at org.apache.struts2.interceptor.CheckboxInterceptor.intercept(CheckboxInterceptor.java:91)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:246)
	at com.opensymphony.xwork2.interceptor.PrepareInterceptor.doIntercept(PrepareInterceptor.java:171)
	at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:98)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:246)
	at org.apache.struts2.interceptor.ServletConfigInterceptor.intercept(ServletConfigInterceptor.java:164)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:246)
	at com.opensymphony.xwork2.interceptor.ExceptionMappingInterceptor.intercept(ExceptionMappingInterceptor.java:189)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:246)
	at com.opensymphony.xwork2.interceptor.ChainingInterceptor.intercept(ChainingInterceptor.java:145)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:246)
	at org.apache.struts2.impl.StrutsActionProxy.execute(StrutsActionProxy.java:54)
	at org.apache.struts2.dispatcher.Dispatcher.serviceAction(Dispatcher.java:562)
	at org.apache.struts2.dispatcher.ng.ExecuteOperations.executeAction(ExecuteOperations.java:77)
	at org.apache.struts2.dispatcher.ng.filter.StrutsPrepareAndExecuteFilter.doFilter(StrutsPrepareAndExecuteFilter.java:99)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.os.filter.DisableUrlSessionFilter.doFilter(DisableUrlSessionFilter.java:106)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:203)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
	at com.googlecode.psiprobe.Tomcat70AgentValve.invoke(Tomcat70AgentValve.java:38)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:193)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:313)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)


As i said 500 columns configured in Xdoc report.
report calls a java method which returns map that contains 500 keys and each of its value contains a map of - >configured columns and its value (800 columns and its values)

with these number of data results in a java.lang.OutOfMemoryError: Java heap space.

**Comment by angelozerr** [comment]
I suggest you that you create a simple Java Main with Pojo which causes your problem and you share your docx+java Main + Pojo (which can be executed simply (no need installed DB, no compilation pb, etc) in order to I can debug it. Without that, I cannot help you more.

**Comment by premmasarani** [comment]
hi,

Here i have attached my docx, java main and a helper class which returns the result map.
Similar kind of logic is used in my web application and here for ease i have returned the static data as a result.
It will work fine as a java application but the same code will give java heap space when called from web application as it uses tomcat's memory.
 
[XDocReport.class.txt](https://github.com/opensagres/xdocreport/files/37735/XDocReport.class.txt)
[XDocReportHelper.class.txt](https://github.com/opensagres/xdocreport/files/37736/XDocReportHelper.class.txt)
[testXdocReport.docx](https://github.com/opensagres/xdocreport/files/37737/testXdocReport.docx)

**Comment by premmasarani** [comment]
hi,

Here i have attached my docx, java main and a helper class which returns the result map.
Similar kind of logic is used in my web application and here for ease i have returned the static data as a result.
It will work fine as a java application but the same code will give java heap space when called from web application as it uses tomcat's memory.

[XDocReport.java.txt](https://github.com/opensagres/xdocreport/files/37800/XDocReport.java.txt)
[XDocReportHelper.java.txt](https://github.com/opensagres/xdocreport/files/37801/XDocReportHelper.java.txt)
[testXdocReport.docx](https://github.com/opensagres/xdocreport/files/37802/testXdocReport.docx)

**Comment by premmasarani** [comment]
hi angelozerr, waiting for your reply on this.

**Comment by angelozerr** [comment]
> It will work fine as a java application 

So I cannot debug your problem with your attached files, because it will work.

> but the same code will give java heap space when called from web application as it uses tomcat's memory.

Have you tested inside your web application but with static data model (defined in your XDOcReportHelper). Perhaps you need to add more memory for your tomcat.

Good luck

**Comment by premlathiya** [comment]
angelozerr, 
Yes we can increase memory of tomcat. But it is not a permanent fix of this issue.
Increasing memory is not at all solution every time right?

Here in this case we are giving input as a Map in context : 
Main Map(String, Map)  size is 500 and each value of main Map  is again Map(String,String)  (Having size of 800)

So docx report library need to iterate 500*800 = 400000 times max to find record.
So why it consume this much memory?
Is Docx report is not capable of handling such data?

Have you go through our implementation source attached? anything wrong we doing? and alternative approach for this?

Your help & guidance is very useful for us if you can. :)

**Comment by angelozerr** [comment]
Your stack trace is not very helpful. We should know which part throw an error. https://github.com/opensagres/xdocreport/blob/master/document/fr.opensagres.xdocreport.document/src/main/java/fr/opensagres/xdocreport/document/AbstractXDocReport.java#L494

 * internalGetTemplateEngine() ? https://github.com/opensagres/xdocreport/blob/master/document/fr.opensagres.xdocreport.document/src/main/java/fr/opensagres/xdocreport/document/AbstractXDocReport.java#L508
           
 * processTemplateEngine?
 * ...

Is Docx report is not capable of handling such data? Never generated so big file, I don't know.

**Comment by premmasarani** [comment]
hi,
here is the full stack trace.
[stack_trace.txt](https://github.com/opensagres/xdocreport/files/41498/stack_trace.txt)

**Comment by angelozerr** [comment]
As I said you, I cannot do nothing with your stacktrace.
