### ISSUE TITLE
Html style inside loop breaks the template

### ISSUE THREAD

**Issue by kevinsdooapp** [opensagres/xdocreport#89]
In a huge object loop (a project bean), I need to display in the report an html field value for wich project.

I read the documentation and successfully display a simple html field outside loop. But is it not possible to make it work in loop. How to do it?

You can checkout a simple template example that fail here https://github.com/kevinsdooapp/xdocreport-issue-77.git (I reused a now useless repository ;))

**Comment by angelozerr** [comment]
At first in your sample https://github.com/kevinsdooapp/xdocreport-issue-77/blob/master/src/main/java/Main.java you do:

```java
report.createFieldsMetadata().addFieldAsTextStyling("htmlOutsideLoop", SyntaxKind.Html);
report.createFieldsMetadata().addFieldAsTextStyling("htmlInsideLoop", SyntaxKind.Html);
```

The "htmlOutsideLoop" will be ignored, you must do:

```java
FieldsMetadata metadata = report.createFieldsMetadata();
metadata .addFieldAsTextStyling("htmlOutsideLoop", SyntaxKind.Html);
metadata .addFieldAsTextStyling("htmlInsideLoop", SyntaxKind.Html);
```

For the loop, I don't remember if it is supported, but I suggest you to try:

```java
FieldsMetadata metadata = report.createFieldsMetadata();
metadata .addFieldAsTextStyling("htmlOutsideLoop", SyntaxKind.Html);
metadata .addFieldAsTextStyling("htmlInsideLoop", SyntaxKind.Html).addFieldAsList("htmlInsideLoop");
```

or

```java
FieldsMetadata metadata = report.createFieldsMetadata();
metadata .addFieldAsTextStyling("htmlOutsideLoop", SyntaxKind.Html);
metadata .addField("htmlInsideLoop", true, null, SyntaxKind.Html, false).
```

**Comment by kevinsdooapp** [comment]
Hi tried both solutions but there is always a parsing exception.
```
Exception in thread "main" org.apache.velocity.exception.ParseErrorException: Encountered "(" at fr.opensagres.xdocreport.document.docx.DocxReport@1807454!word/document.xml[line 1, column 1518]
Was expecting one of:
    "[" ...
    "}" ...
    
	at org.apache.velocity.Template.process(Template.java:151)
	at org.apache.velocity.runtime.resource.ResourceManagerImpl.loadResource(ResourceManagerImpl.java:437)
	at org.apache.velocity.runtime.resource.ResourceManagerImpl.getResource(ResourceManagerImpl.java:352)
	at org.apache.velocity.runtime.RuntimeInstance.getTemplate(RuntimeInstance.java:1533)
	at org.apache.velocity.app.VelocityEngine.getTemplate(VelocityEngine.java:392)
	at fr.opensagres.xdocreport.template.velocity.internal.VelocityTemplateEngine.processWithCache(VelocityTemplateEngine.java:97)
	at fr.opensagres.xdocreport.template.AbstractTemplateEngine.process(AbstractTemplateEngine.java:112)
	at fr.opensagres.xdocreport.template.AbstractTemplateEngine.process(AbstractTemplateEngine.java:83)
	at fr.opensagres.xdocreport.document.AbstractXDocReport.processTemplateEngine(AbstractXDocReport.java:775)
	at fr.opensagres.xdocreport.document.AbstractXDocReport.process(AbstractXDocReport.java:521)
	at fr.opensagres.xdocreport.document.AbstractXDocReport.process(AbstractXDocReport.java:487)
	at Main.generateReport(Main.java:58)
	at Main.main(Main.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

**Comment by angelozerr** [comment]
Ok so it seems that I had not supported it.

**Comment by kevinsdooapp** [comment]
Could you indicate me the class to update to manage it? I'll create a pull request if I make it work ;)

**Comment by angelozerr** [comment]
To be honnest with you, I don't remember how it works, it was so a long time that I have developped that.

**Comment by kevinsdooapp** [comment]
The problem was that registered html fields are transformed even on instruction fields. I fixed it and did a pull request

**Comment by kevinsdooapp** [comment]
Hi,
My pull request is still waiting. Did you have a look?
Thank you in advance
Kevin

**Comment by kevinsdooapp** [comment]
@angelozerr As you, the fix which I did for this issue covered only Velocity. I'm please to announce you that I have also fix it for Freemarker. I updated the test case Issue89Test to covert Freemarker. Can you review the pull request and merge it?

You'll notice that I've also update the test case Issue93 to help you to reproduce and fix it (since I didn't succeeded myself. Don't forget to uncomment the @Ignore annotation on this test case).

Thank you in advance!

Kévin

**Comment by kevinsdooapp** [comment]
My pull-request is still waiting. It's really unconfortable to maintain an xdocreport fork in parralel of the official one, especially when the project continue to be improved.
Could be nice to have a look of the fix ;)

Thank you for your understanding

**Comment by angelozerr** [comment]
I understand your frustation @kevinsdooapp but it's very hard for to find time today for XDocReport. I have commented your PR at https://github.com/opensagres/xdocreport/pull/92/files#r147551384

**Comment by kevinsdooapp** [comment]
Thank you @angelozerr . I also understrand that it's hard to find time, that's why test case with pull request are important to help you to maintain the project and keep it in life.
I'll update my PR according to your comment as soon as possible.
Thank you

**Comment by angelozerr** [comment]
>  why test case with pull request are important to help you to maintain the project and keep it in life.

Exactly!

> I'll update my PR according to your comment as soon as possible.

Please update your code like I have suggested and after I could accept your PR.
