### ISSUE TITLE
[Solved] Converting odt to pdf with IText 5.x

### ISSUE THREAD

**Issue by pensionarchitects-ben** [opensagres/xdocreport#94]
I am not able to get the conversion to work with odt to pdf using IText 5.x. Is there a guide or a sample that addresses this or can someone help me with it?

I am using maven with these dependencies:

        <dependency>
	  	<groupId>fr.opensagres.xdocreport</groupId>
	  	<artifactId>org.odftoolkit.odfdom.converter.pdf.itext5</artifactId>
	  	<version>1.0.5</version>
	</dependency>
	<dependency>
		<groupId>com.itextpdf</groupId>
		<artifactId>itextpdf</artifactId>
		<version>5.4.1</version>
      </dependency>

Using this code:

        try {
		File file = new File("./test.odt");
		File output = new File("./pdf.pdf");
	        OdfTextDocument document = OdfTextDocument.loadDocument( new FileInputStream(file));
	        OutputStream out = new FileOutputStream( output );
	        PdfOptions options = getPdfOptions();

	        PdfConverter.getInstance().convert( document, out, options );
           } catch (Exception e) {
			//
	   }

**Comment by angelozerr** [comment]
> I am not able to get the conversion to work with odt to pdf using IText 5.x.

What is your problem, have you a stack trace?

**Comment by pensionarchitects-ben** [comment]
Here is the stacktrace, forgot to add it in.

Exception in thread "main" java.lang.NoSuchMethodError: org.odftoolkit.odfdom.converter.pdf.internal.stylable.StylableParagraph.getChunks()Ljava/util/List;
	at org.odftoolkit.odfdom.converter.pdf.internal.stylable.StylableParagraph.postProcessEmptyParagraph(StylableParagraph.java:224)
	at org.odftoolkit.odfdom.converter.pdf.internal.stylable.StylableParagraph.getElement(StylableParagraph.java:212)
	at org.odftoolkit.odfdom.converter.pdf.internal.ElementVisitorForIText.addITextContainer(ElementVisitorForIText.java:830)
	at org.odftoolkit.odfdom.converter.pdf.internal.ElementVisitorForIText.addITextContainer(ElementVisitorForIText.java:818)
	at org.odftoolkit.odfdom.converter.pdf.internal.ElementVisitorForIText.processParagraphOrHeading(ElementVisitorForIText.java:383)
	at org.odftoolkit.odfdom.converter.pdf.internal.ElementVisitorForIText.visit(ElementVisitorForIText.java:321)
	at org.odftoolkit.odfdom.dom.element.text.TextPElement.accept(TextPElement.java:1681)
	at org.odftoolkit.odfdom.converter.core.ElementVisitorConverter.visit(ElementVisitorConverter.java:82)
	at org.odftoolkit.odfdom.dom.DefaultElementVisitor.visit(DefaultElementVisitor.java:2861)
	at org.odftoolkit.odfdom.converter.pdf.internal.ElementVisitorForIText.visit(ElementVisitorForIText.java:235)
	at org.odftoolkit.odfdom.dom.element.style.StyleFooterElement.accept(StyleFooterElement.java:420)
	at org.odftoolkit.odfdom.converter.core.ElementVisitorConverter.visit(ElementVisitorConverter.java:82)
	at org.odftoolkit.odfdom.dom.DefaultElementVisitor.visit(DefaultElementVisitor.java:2965)
	at org.odftoolkit.odfdom.converter.pdf.internal.ElementVisitorForIText.visit(ElementVisitorForIText.java:188)
	at org.odftoolkit.odfdom.dom.element.style.StyleMasterPageElement.accept(StyleMasterPageElement.java:707)
	at org.odftoolkit.odfdom.converter.core.ElementVisitorConverter.visit(ElementVisitorConverter.java:82)
	at org.odftoolkit.odfdom.dom.DefaultElementVisitor.visit(DefaultElementVisitor.java:2541)
	at org.odftoolkit.odfdom.dom.element.office.OfficeMasterStylesElement.accept(OfficeMasterStylesElement.java:109)
	at org.odftoolkit.odfdom.converter.pdf.PdfConverter.processBody(PdfConverter.java:123)
	at org.odftoolkit.odfdom.converter.pdf.PdfConverter.doConvert(PdfConverter.java:65)
	at org.odftoolkit.odfdom.converter.pdf.PdfConverter.doConvert(PdfConverter.java:1)
	at org.odftoolkit.odfdom.converter.core.AbstractODFConverter.convert(AbstractODFConverter.java:42)
	at App.convert(App.java:59)
	at App.run(App.java:46)
	at be.pensionarchitects.cli.AppRunner.run(AppRunner.java:18)
	at App.main(App.java:33)

**Comment by angelozerr** [comment]
That's strange, it seems that it can find com.itextpdf JARs?

**Comment by pensionarchitects-ben** [comment]
Okay found out the problem, there was some conflict with maven and eclipse and it added an old version of IText 5 where that method was a bit different. But now it works.
