### ISSUE TITLE
Strange issue when ODT file is re-saved after re-typing a part of parameter name

### ISSUE THREAD

**Issue by erobic** [opensagres/xdocreport#99]
I have attached two very simple, single-parameter, seemingly identical ODT templates created using LibreWriter 5.0

[param-name-error.odt.zip](https://github.com/opensagres/xdocreport/files/60376/param-name-error.odt.zip)
[param-name-ok.odt.zip](https://github.com/opensagres/xdocreport/files/60377/param-name-ok.odt.zip)

Each file has single parameter ${paramName}.

Both files are virtually identical EXCEPT that I did this to: param-name-error.odt
* I deleted "e" character from "${paramName}" and saved the file template. i.e. file content was ${paramNam}
* Then I re-typed the "e" character and saved again. So, currently, it still has the parameter name as: ${paramName}

Code runs for: param-name-ok.odt, however it throws exception for param-name-error.odt.

```
Exception in thread "main" 13:41:43.912 [main] DEBUG f.o.x.t.AbstractTemplateEngine - End template engine id=Freemarker_2.3.x for the entry=content.xml done with 8(ms).
13:41:43.912 [main] DEBUG f.o.x.d.AbstractXDocReport - End process report with error done with 36(ms).
freemarker.core.ParseException: Syntax error in template "fr.opensagres.xdocreport.document.odt.ODTReport@6ef81f31!content.xml" in line 4, column 3563:
Encountered ":", but was expecting one of:
    ".."
    <DOT_DOT_LESS>
    "..*"
    "}"
    "."
    "["
    "("
    "?"
    "!"
    <TERMINATING_EXCLAM>
    "??"
    "+"
    "-"
    "*"
    "/"
    "%"
    "!="
    "="
    "=="
    <AND>
    <OR>
	at freemarker.core.FMParser.generateParseException(FMParser.java:5251)
	at freemarker.core.FMParser.jj_consume_token(FMParser.java:5122)
	at freemarker.core.FMParser.StringOutput(FMParser.java:1243)
	at freemarker.core.FMParser.MixedContent(FMParser.java:3036)
	at freemarker.core.FMParser.OptionalBlock(FMParser.java:3253)
	at freemarker.core.FMParser.Escape(FMParser.java:2755)
	at freemarker.core.FMParser.FreemarkerDirective(FMParser.java:2903)
	at freemarker.core.FMParser.MixedContent(FMParser.java:3081)
	at freemarker.core.FMParser.OptionalBlock(FMParser.java:3253)
	at freemarker.core.FMParser.Root(FMParser.java:3432)
	at freemarker.template.Template.<init>(Template.java:208)
	at freemarker.cache.TemplateCache.loadTemplate(TemplateCache.java:495)
	at freemarker.cache.TemplateCache.getTemplate(TemplateCache.java:409)
	at freemarker.cache.TemplateCache.getTemplate(TemplateCache.java:261)
	at freemarker.template.Configuration.getTemplate(Configuration.java:1786)
	at freemarker.template.Configuration.getTemplate(Configuration.java:1646)
	at fr.opensagres.xdocreport.template.freemarker.FreemarkerTemplateEngine.processWithCache(FreemarkerTemplateEngine.java:110)
	at fr.opensagres.xdocreport.template.AbstractTemplateEngine.process(AbstractTemplateEngine.java:112)
	at fr.opensagres.xdocreport.template.AbstractTemplateEngine.process(AbstractTemplateEngine.java:83)
	at fr.opensagres.xdocreport.document.AbstractXDocReport.processTemplateEngine(AbstractXDocReport.java:775)
	at fr.opensagres.xdocreport.document.AbstractXDocReport.convert(AbstractXDocReport.java:703)
	at fr.opensagres.xdocreport.document.AbstractXDocReport.convert(AbstractXDocReport.java:673)
	at com.erobic.converter.OdtToPdfConverter.generatePdf(OdtToPdfConverter.java:35)
	at com.erobic.openSagresIssues.ParamNameIssueRunner.createPdf(ParamNameIssueRunner.java:50)
	at com.erobic.openSagresIssues.ParamNameIssueRunner.runParamNameError(ParamNameIssueRunner.java:42)
	at com.erobic.openSagresIssues.ParamNameIssueRunner.main(ParamNameIssueRunner.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
```
I am using this piece of code to generate pdf:
```
   public File generatePdf(String templateName, Map<String, Object> paramMap, String fullFileName) throws Exception {
        InputStream templateStream = this.getClass().getResourceAsStream("/" + templateName);
        IXDocReport report = XDocReportRegistry.getRegistry().loadReport(templateStream, TemplateEngineKind.Freemarker);
        Options options = Options.getTo(ConverterTypeTo.PDF).via(ConverterTypeVia.ODFDOM);
        File outputFile = new File(fullFileName);
        OutputStream outputStream = new FileOutputStream(outputFile);
        report.convert((Map<String, Object>) (Map<String, ?>) paramMap, options, outputStream);
        outputStream.close();
        return outputFile;
    }
```

What is the problem?

**Comment by pensionarchitects-ben** [comment]
The odt with the error is not created correctly, if you check the content.xml from the odt you can see it has 
<text:p text:style-name="P3">${paramNam<text:span text:style-name="T1">e</text:span>}</text:p>
what is needed is <text:p text:style-name="P3">${paramName}</text:p>

**Comment by angelozerr** [comment]
@erobic I suggest you that you read https://github.com/opensagres/xdocreport/wiki/ODTDesignReport You cannot write your field directly inside ODT. You must use input field.

**Comment by erobic** [comment]
Ok thank you :-)
